// GENERATED by scripts/build-static-demo.js; virtual browser-only review.
(() => {
  'use strict';
  if (window.PAICHONG_DEMO_MODE !== true) return;
  const nativeFetch = window.fetch.bind(window);
  const kind = window.PAICHONG_PORTAL_KIND === 'client' ? 'client' : 'workbench';
  const basePath = new URL('.', window.location.href).pathname;
  const prefix = `paichong-static-demo-v1:${basePath}:${kind}:`;
  const dataKey = prefix + 'data', sessionsKey = prefix + 'sessions';
  const local = window.localStorage;
  const accounts = {
    '13800138000': { password: 'user123', role: 'user', name: '用户演示账号' },
    '13800138001': { password: 'user123', role: 'user', name: '第二用户演示账号' },
    ops001: { password: 'ops123', role: 'ops', name: '总部运营演示账号' },
    driver001: { password: 'driver123', role: 'driver', name: '刘师傅', driverId: 'DRV-001' },
    driver002: { password: 'driver123', role: 'driver', name: '陈师傅', driverId: 'DRV-002' },
    driver003: { password: 'driver123', role: 'driver', name: '王师傅', driverId: 'DRV-003' },
    partner001: { password: 'partner123', role: 'partner', name: '天河合作机构', nodeId: 'NODE-GZ-TH' },
    partner002: { password: 'partner123', role: 'partner', name: '白云合作机构', nodeId: 'NODE-GZ-BY' }
  };
  const allowed = (role) => kind === 'client' ? role === 'user' : ['ops', 'driver', 'partner'].includes(role);
  function randomHex(size) {
    const bytes = new Uint8Array(size);
    window.crypto.getRandomValues(bytes);
    return Array.from(bytes, (byte) => byte.toString(16).padStart(2, '0')).join('');
  }
  const browserCrypto = {
    randomBytes: (size) => ({ toString: () => randomHex(size) }),
    randomUUID: () => window.crypto.randomUUID ? window.crypto.randomUUID() : `${randomHex(4)}-${randomHex(2)}-4${randomHex(2).slice(1)}-8${randomHex(2).slice(1)}-${randomHex(6)}`
  };
  const modules = { "./store": function(module, exports, require) {
const { randomBytes } = require('node:crypto');

class StoreError extends Error {
  constructor(message, status = 400, code = 'BAD_REQUEST') {
    super(message);
    this.status = status;
    this.code = code;
  }
}

function demoData() {
  const oldOrder = (id, phone, petName, petType, weight, fromCity, toCity, price) => ({
    id, userPhone: phone, contactName: '演示客户', petName, petType, breed: '演示品种', weight,
    fromCity, toCity, status: '待拼单', reviewStatus: 'confirmed', reviewNote: '模拟审核已通过',
    depositStatus: '已支付', deposit: { amount: Math.round(price * 0.2), status: 'paid', paidAt: '2026-08-28T10:29:00.000Z', method: '模拟微信支付' },
    quote: { id: `Q-${id}`, basePrice: price, extraFeeMin: 0, extraFeeMax: 200, totalMin: price, totalMax: price + 200, depositAmount: Math.round(price * 0.2), estimatedDays: '2-4天', simulated: true },
    priceEstimate: price, materials: { vaccineCertificate: `${petName}_免疫证明.jpg`, petPhoto: `${petName}_近照.jpg` },
    pickup: null, assignedNode: null, capacityHeld: false, routeId: '', isDemo: true,
    createdAt: '2026-08-28T10:26:00.000Z', updatedAt: '2026-08-28T10:29:00.000Z', reviewHistory: []
  });
  return {
    demo: { enabled: true, label: '甲方评审演示数据', resetAt: null },
    orders: [
      oldOrder('PC20260828001', '13800000001', '豆包', '猫', 5, '广州', '北京', 980),
      oldOrder('PC20260828002', '13800000002', '团子', '猫', 4.2, '武汉', '郑州', 760),
      oldOrder('PC20260828003', '13800000003', '阿福', '犬', 12, '郑州', '北京', 1280)
    ],
    routes: [{
      id: 'LINE-20260906-GZBJ', name: '广州—武汉—郑州—北京', departureAt: '2026-09-06T07:30:00.000Z', driver: '刘师傅',
      minOrders: 5, maxWaitingHours: 36, capacity: 8, status: '凑单中', orderIds: [],
      nodes: [{ city: '广州', capacity: 8, used: 2 }, { city: '武汉', capacity: 8, used: 4 }, { city: '郑州', capacity: 8, used: 3 }, { city: '北京', capacity: 8, used: 5 }]
    }],
    cityNodes: [
      { id: 'NODE-GZ-TH', city: '广州', name: '天河合作交接点', capacity: 3, occupied: 1, open: '09:00-20:00', status: '正常' },
      { id: 'NODE-GZ-BY', city: '广州', name: '白云合作交接点', capacity: 5, occupied: 2, open: '09:00-20:00', status: '正常' },
      { id: 'NODE-WH-HK', city: '武汉', name: '汉口合作交接点', capacity: 4, occupied: 1, open: '09:00-20:00', status: '正常' },
      { id: 'NODE-ZZ-JS', city: '郑州', name: '金水合作交接点', capacity: 4, occupied: 1, open: '09:00-20:00', status: '正常' },
      { id: 'NODE-BJ-CY', city: '北京', name: '朝阳合作交接点', capacity: 6, occupied: 3, open: '09:00-20:00', status: '正常' }
    ],
    availability: [
      { id: 'SLOT-GZ-0904-AM', city: '广州', date: '2026-09-04', timeSlot: '09:00-12:00', capacity: 4, occupied: 1 },
      { id: 'SLOT-GZ-0904-PM', city: '广州', date: '2026-09-04', timeSlot: '13:00-16:00', capacity: 4, occupied: 3 },
      { id: 'SLOT-GZ-0905-AM', city: '广州', date: '2026-09-05', timeSlot: '09:00-12:00', capacity: 4, occupied: 2 },
      { id: 'SLOT-GZ-0905-PM', city: '广州', date: '2026-09-05', timeSlot: '13:00-16:00', capacity: 4, occupied: 1 },
      { id: 'SLOT-WH-0904-AM', city: '武汉', date: '2026-09-04', timeSlot: '09:00-12:00', capacity: 3, occupied: 1 },
      { id: 'SLOT-WH-0904-PM', city: '武汉', date: '2026-09-04', timeSlot: '13:00-16:00', capacity: 3, occupied: 2 },
      { id: 'SLOT-WH-0905-AM', city: '武汉', date: '2026-09-05', timeSlot: '09:00-12:00', capacity: 3, occupied: 0 },
      { id: 'SLOT-ZZ-0905-AM', city: '郑州', date: '2026-09-05', timeSlot: '09:00-12:00', capacity: 3, occupied: 1 },
      { id: 'SLOT-BJ-0905-AM', city: '北京', date: '2026-09-05', timeSlot: '09:00-12:00', capacity: 4, occupied: 2 }
    ],
    auditLogs: []
  };
}

const ROUTE_PRICES = {
  '广州|武汉': [1280, '2-3天'], '广州|郑州': [1580, '3-4天'], '广州|北京': [1880, '3-4天'],
  '武汉|郑州': [760, '1-2天'], '武汉|北京': [1280, '2-3天'], '郑州|北京': [980, '1-2天']
};

function shanghaiDate() {
  const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Shanghai', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date());
  const value = (type) => parts.find((part) => part.type === type).value;
  return `${value('year')}-${value('month')}-${value('day')}`;
}
function addDays(date, days) { return new Date(Date.parse(`${date}T00:00:00Z`) + days * 86400000).toISOString().slice(0, 10); }
function bookingWindow() { const today = shanghaiDate(); return { today, minDate: addDays(today, 1), maxDate: addDays(today, 14) }; }
const operations = require('./operations')({ StoreError, shanghaiDate, addDays, log });
const partners = require('./partners')({ StoreError, operations, shanghaiDate, addDays, log });
const fulfillment = require('./fulfillment')({ StoreError, moneyValue, log });
function hydrate(data) {
  data.availability ||= [];
  const { today } = bookingWindow();
  const cityCodes = { 广州: 'GZ', 武汉: 'WH', 郑州: 'ZZ', 北京: 'BJ' };
  const cities = [...new Set((data.cityNodes || []).map((node) => node.city))];
  for (const city of cities) for (let offset = 1; offset <= 14; offset += 1) {
    const date = addDays(today, offset);
    for (const [period, timeSlot] of [['AM', '09:00-12:00'], ['PM', '13:00-16:00']]) {
      if (data.availability.some((slot) => slot.city === city && slot.date === date && slot.timeSlot === timeSlot)) continue;
      data.availability.push({ id: `SLOT-${cityCodes[city] || encodeURIComponent(city)}-${date.replaceAll('-', '')}-${period}`, city, date, timeSlot, capacity: ['广州', '北京'].includes(city) ? 4 : 3, occupied: 0 });
    }
  }
  for (const order of data.orders || []) {
    order.ownerAccount ||= order.userPhone;
    order.reviewHistory ||= [];
    if (!order.reviewStatus && ['已驳回', '已取消'].includes(order.status)) order.reviewStatus = order.status === '已驳回' ? 'rejected' : 'cancelled';
    if (order.proposedPrice == null && order.finalPrice != null) order.proposedPrice = order.finalPrice;
    if (order.reviewStatus === 'confirmed' && order.confirmedPrice == null) order.confirmedPrice = order.proposedPrice ?? order.quote?.basePrice ?? order.priceEstimate;
    const refundStatus = { refunding: 'pending', refund_failed: 'failed', refunded: 'succeeded' }[order.deposit?.status];
    if (!order.refund && ['rejected', 'cancelled'].includes(order.reviewStatus) && refundStatus) {
      order.refund = {
        id: `RF-${order.id}`, status: refundStatus, amount: order.deposit.amount,
        reason: order.cancelReason || order.reviewNote || '历史订单保证金退款',
        requestedAt: order.rejectedAt || order.cancelledAt || order.updatedAt || order.createdAt,
        updatedAt: order.updatedAt || order.createdAt, attempts: 0, simulated: true
      };
      if (refundStatus === 'succeeded') order.refund.completedAt = order.deposit.refundedAt || order.updatedAt || order.createdAt;
    }
  }
  return partners.hydrate(operations.hydrate(data));
}
function read() { return hydrate(readDemoData()); }
function write(data) { writeDemoData(data); return data; }
function log(data, action, operator = '运营演示账号', payload = {}) {
  data.auditLogs ||= [];
  data.auditLogs.unshift({ id: `LOG-${Date.now()}-${Math.random().toString(16).slice(2, 6)}`, action, operator, payload, createdAt: new Date().toISOString(), simulated: true });
  data.auditLogs = data.auditLogs.slice(0, 200);
}
function required(value, label) { const text = String(value || '').trim(); if (!text) throw new StoreError(`请填写${label}`); return text; }
function petTypeOf(value) {
  const valueLower = String(value || '').trim().toLowerCase();
  if (['猫', '猫咪', 'cat'].includes(valueLower)) return '猫';
  if (['犬', '狗', '狗狗', 'dog'].includes(valueLower)) return '犬';
  throw new StoreError('宠物类型仅支持猫或犬');
}
function findOrder(data, id) { const order = data.orders.find((item) => item.id === id); if (!order) throw new StoreError('未找到订单', 404, 'ORDER_NOT_FOUND'); return order; }
function accountValue(account) { return required(typeof account === 'object' ? account?.account : account, '登录账号'); }
function ownerOf(order) { return order.ownerAccount || order.userPhone; }
function moneyValue(value, label = '金额') {
  if (value === '' || value == null || typeof value === 'boolean' || !['string', 'number'].includes(typeof value)) throw new StoreError(`${label}须为有效正数`);
  const amount = Number(value), cents = Math.round(amount * 100);
  if (!Number.isFinite(amount) || amount <= 0 || !Number.isSafeInteger(cents)) throw new StoreError(`${label}须为有效正数`);
  if (Math.abs(amount * 100 - cents) > 0.000001) throw new StoreError(`${label}最多保留两位小数`);
  return cents / 100;
}
function validateSlot(data, slotId, city, held = false) {
  const slot = data.availability.find((item) => item.id === slotId);
  if (!slot) throw new StoreError('未找到所选接宠时段', 409, 'SLOT_UNAVAILABLE');
  if (slot.city !== city) throw new StoreError('所选接宠时段与出发城市不匹配');
  const { minDate, maxDate } = bookingWindow();
  if (slot.date < minDate || slot.date > maxDate) throw new StoreError('所选接宠时段已过期或不在可预约范围，请重新选择', 409, 'SLOT_EXPIRED');
  if (!held && slot.occupied >= slot.capacity) throw new StoreError('所选时段已约满，请重新选择', 409, 'CAPACITY_FULL');
  return slot;
}
function releaseCapacity(data, order, now) {
  if (!order.capacityHeld) return;
  const slot = data.availability.find((item) => item.id === order.pickup?.slotId);
  if (slot) slot.occupied = Math.max(0, slot.occupied - 1);
  order.capacityHeld = false;
  order.capacityReleasedAt = now;
}
function startRefund(order, reason, now) {
  if (order.deposit?.status !== 'paid') return;
  order.refund = { id: `RF-${order.id}`, status: 'pending', amount: order.deposit.amount, reason, requestedAt: now, updatedAt: now, attempts: 0, simulated: true };
  order.deposit.status = 'refunding'; order.depositStatus = '退款中';
}

function createQuote(input = {}) {
  const fromCity = required(input.fromCity || input.origin, '出发城市');
  const toCity = required(input.toCity || input.destination, '目的城市');
  if (fromCity === toCity) throw new StoreError('出发城市和目的城市不能相同');
  const petType = petTypeOf(input.petType || input.type);
  const weight = Number(input.weight || 0);
  if (!Number.isFinite(weight) || weight <= 0 || weight > 80) throw new StoreError('宠物体重需在 0-80kg 之间');
  const route = ROUTE_PRICES[`${fromCity}|${toCity}`] || ROUTE_PRICES[`${toCity}|${fromCity}`] || [1480, '3-5天'];
  const basePrice = route[0] + (weight > 10 ? Math.ceil((weight - 10) / 5) * 100 : 0);
  return {
    id: `Q-${Date.now()}-${Math.random().toString(16).slice(2, 6).toUpperCase()}`, fromCity, toCity, petType, weight,
    serviceType: input.serviceType || '专车门到门', basePrice, extraFeeMin: 0, extraFeeMax: 200,
    totalMin: basePrice, totalMax: basePrice + 200, depositRate: 0.2, depositAmount: Math.round(basePrice * 0.2), estimatedDays: route[1],
    priceNote: '模拟预估价格；运营建议价经用户确认后用于方案确认，后续司机验宠锁价另行确认。',
    validUntil: new Date(Date.now() + 86400000).toISOString(), simulated: true
  };
}

function listAvailability(query = {}) {
  let items = read().availability || [];
  const { minDate, maxDate } = bookingWindow();
  items = items.filter((slot) => slot.date >= minDate && slot.date <= maxDate);
  if (query.city || query.fromCity) items = items.filter((slot) => slot.city === (query.city || query.fromCity));
  if (query.date) items = items.filter((slot) => slot.date === query.date);
  return items.sort((a, b) => a.date.localeCompare(b.date) || a.timeSlot.localeCompare(b.timeSlot)).map((slot) => ({ ...slot, remaining: Math.max(0, slot.capacity - slot.occupied), available: slot.occupied < slot.capacity, simulated: true }));
}
function availabilityMeta(query = {}) {
  const dates = [...new Set(listAvailability({ city: query.city || query.fromCity }).filter((slot) => slot.available).map((slot) => slot.date))];
  return { ...bookingWindow(), availableDates: dates, nextAvailableDate: dates.find((date) => !query.date || date >= query.date) || dates[0] || null };
}

function normalizeMaterials(input = {}) {
  const source = input.materials || input.files || {};
  const filename = (...keys) => {
    const candidate = keys.map((key) => source[key] || input[key]).find(Boolean);
    return String(typeof candidate === 'object' ? candidate.name || candidate.filename || '' : candidate || '').trim();
  };
  return {
    vaccineCertificate: filename('vaccineCertificate', 'vaccinationCertificate', 'vaccine'),
    petPhoto: filename('petPhoto', 'photo'), standingPhoto: filename('standingPhoto', 'fullBodyPhoto'),
    other: Array.isArray(source.other) ? source.other.map((item) => typeof item === 'string' ? item : item.name || item.filename).filter(Boolean) : []
  };
}

function createOrder(input = {}, account) {
  const data = read();
  const ownerAccount = accountValue(account), userPhone = ownerAccount;
  const contactPhone = String(input.contactPhone || input.contact?.phone || input.userPhone || input.phone || userPhone).trim();
  if (!/^1\d{10}$/.test(contactPhone)) throw new StoreError('请填写正确的 11 位联系手机号');
  const pet = input.pet || {}, quoteInput = input.quote || {}, pickupInput = input.pickup || {};
  const petName = required(input.petName || pet.name, '宠物名称');
  const petType = petTypeOf(input.petType || pet.type);
  const weight = Number(input.weight || pet.weight || 0);
  const fromCity = required(input.fromCity || input.origin || quoteInput.fromCity, '出发城市');
  const toCity = required(input.toCity || input.destination || quoteInput.toCity, '目的城市');
  const quote = createQuote({ fromCity, toCity, petType, weight, serviceType: quoteInput.serviceType || input.serviceType });
  const materials = normalizeMaterials(input);
  if (!materials.vaccineCertificate || !materials.petPhoto) throw new StoreError('请提交免疫证明和宠物近照文件名');
  const healthInput = input.healthDeclaration || input.health || {};
  const healthKeys = ['noDisease', 'notPregnant', 'safeHandling'];
  if (!healthKeys.every((key) => Array.isArray(healthInput) ? healthInput.includes(key) : healthInput[key] === true)) throw new StoreError('请确认全部三项健康声明', 400, 'HEALTH_DECLARATION_REQUIRED');
  const slotId = required(input.slotId || input.pickupSlotId || pickupInput.slotId, '接宠时段');
  const details = {
    contactName: String(input.contactName || input.contact?.name || '').trim(), contactPhone,
    pickupAddress: String(input.pickupAddress || pickupInput.address || '').trim(),
    recipientName: String(input.recipientName || input.recipient?.name || '').trim(),
    recipientPhone: String(input.recipientPhone || input.recipient?.phone || '').trim(),
    recipientAddress: String(input.recipientAddress || input.recipient?.address || '').trim(),
    careNote: String(input.careNote || pet.careNote || '').trim()
  };
  if (details.recipientPhone && !/^1\d{10}$/.test(details.recipientPhone)) throw new StoreError('请填写正确的 11 位收宠手机号');
  const breed = String(input.breed || pet.breed || '未填写').trim();
  const clientRequestId = String(input.clientRequestId || '').trim();
  if (clientRequestId.length > 100) throw new StoreError('提交标识过长');
  const requestFingerprint = JSON.stringify({ petName, petType, weight, breed, fromCity, toCity, serviceType: quote.serviceType, slotId, materials, healthDeclaration: healthKeys, ...details });
  if (clientRequestId) {
    const previous = data.orders.find((order) => ownerOf(order) === ownerAccount && order.clientRequestId === clientRequestId);
    if (previous) {
      if (previous.requestFingerprint !== requestFingerprint) throw new StoreError('本次提交标识已用于其他订单资料，请重新提交', 409, 'IDEMPOTENCY_CONFLICT');
      return previous;
    }
  }
  const slot = validateSlot(data, slotId, fromCity);
  const day = shanghaiDate().replaceAll('-', ''), prefix = `PC${day}`;
  const next = data.orders.filter((order) => order.id.startsWith(prefix)).reduce((max, order) => Math.max(max, Number(order.id.slice(prefix.length)) || 0), 0) + 1;
  const now = new Date().toISOString();
  const order = {
    id: `${prefix}${String(next).padStart(3, '0')}`, ownerAccount, userPhone, clientRequestId, requestFingerprint, ...details,
    petName, petType, breed, weight, fromCity, toCity, serviceType: quote.serviceType,
    status: '待支付保证金', reviewStatus: 'not_submitted', reviewNote: '', depositStatus: '待支付',
    deposit: { amount: quote.depositAmount, rate: 0.2, status: 'unpaid', paidAt: null, method: '模拟微信支付' },
    quote, priceEstimate: quote.basePrice, materials, healthDeclaration: healthKeys,
    pickup: { city: slot.city, date: slot.date, timeSlot: slot.timeSlot, slotId: slot.id }, assignedNode: null,
    capacityHeld: false, capacityReleasedAt: null, routeId: '', isDemo: true, createdAt: now, updatedAt: now, reviewHistory: []
  };
  data.orders.unshift(order); log(data, 'USER_ORDER_CREATED', '用户演示账号', { orderId: order.id, phone: userPhone }); write(data); return order;
}

function listUserOrders(account) { const value = accountValue(account); return read().orders.filter((order) => ownerOf(order) === value); }
function getOrder(id) { return findOrder(read(), id); }
function getUserOrder(id, account) {
  const order = getOrder(id);
  if (ownerOf(order) !== accountValue(account)) throw new StoreError('未找到订单', 404, 'ORDER_NOT_FOUND');
  return order;
}

function payDeposit(id) {
  const data = read(), order = findOrder(data, id);
  if (['rejected', 'cancelled'].includes(order.reviewStatus) || ['已驳回', '已取消'].includes(order.status)) throw new StoreError('订单已关闭，不能支付', 409, 'ORDER_CLOSED');
  if (order.deposit?.status === 'paid') return { order, idempotent: true, simulatedPayment: true };
  if (order.deposit?.status !== 'unpaid' || order.reviewStatus !== 'not_submitted') throw new StoreError('当前订单不能支付保证金', 409, 'INVALID_ORDER_STATE');
  const slot = validateSlot(data, order.pickup?.slotId, order.fromCity, order.capacityHeld);
  if (!order.capacityHeld) { slot.occupied += 1; order.capacityHeld = true; order.capacityReleasedAt = null; }
  const now = new Date().toISOString();
  Object.assign(order.deposit, { status: 'paid', paidAt: now, method: '模拟微信支付' });
  Object.assign(order, { depositStatus: '已支付', status: '待审核', reviewStatus: 'pending', updatedAt: now });
  log(data, 'DEMO_DEPOSIT_PAID', '用户演示账号', { orderId: id, amount: order.deposit.amount, slotId: order.pickup.slotId }); write(data);
  return { order, idempotent: false, simulatedPayment: true };
}

function supplementOrder(id, input = {}) {
  const data = read(), order = findOrder(data, id);
  if (order.reviewStatus !== 'info_required') throw new StoreError('当前订单不处于待补件状态', 409, 'INVALID_ORDER_STATE');
  const materials = normalizeMaterials(input), note = String(input.note || '').trim();
  if (!Object.values(materials).flat().filter(Boolean).length && !note) throw new StoreError('请至少补充一份材料或说明');
  order.materials = { ...order.materials, ...Object.fromEntries(Object.entries(materials).filter(([, value]) => Array.isArray(value) ? value.length : value)) };
  order.reviewStatus = 'resubmitted'; order.status = '已补件待复审'; order.supplementNote = note; order.updatedAt = new Date().toISOString();
  order.reviewHistory.push({ action: 'supplement', note, materials, at: order.updatedAt, operator: '用户演示账号', simulated: true });
  log(data, 'USER_ORDER_SUPPLEMENTED', '用户演示账号', { orderId: id, materials }); write(data); return order;
}

function reviewOrder(id, input = {}) {
  const data = read(), order = findOrder(data, id), action = String(input.action || '');
  if (!['request_info', 'approve', 'reject'].includes(action)) throw new StoreError('审核动作仅支持 request_info、approve 或 reject');
  const note = String(input.note || input.reviewNote || '').trim(), now = new Date().toISOString();
  if (['request_info', 'reject'].includes(action) && !note) throw new StoreError(action === 'reject' ? '请填写拒绝承运原因' : '请填写补件说明');
  if ((action === 'approve' && order.reviewStatus === 'approved') || (action === 'reject' && order.reviewStatus === 'rejected')) return { order, idempotent: true };
  if (!['pending', 'resubmitted', 'info_required'].includes(order.reviewStatus) || order.routeId) throw new StoreError('当前订单不能继续审核', 409, 'REVIEW_FINISHED');
  if (order.deposit?.status !== 'paid') throw new StoreError('订单尚未支付保证金', 409, 'DEPOSIT_UNPAID');
  if (action === 'request_info') { if (!note) throw new StoreError('请填写补件说明'); order.reviewStatus = 'info_required'; order.status = '待补材料'; }
  if (action === 'approve') {
    const proposedPrice = moneyValue(input.proposedPrice ?? input.finalPrice ?? order.quote.basePrice, '运营建议价');
    if (proposedPrice < order.deposit.amount) throw new StoreError('运营建议价不能低于已付保证金', 400, 'PRICE_BELOW_DEPOSIT');
    operations.reserve(data, order, input);
    order.reviewStatus = 'approved'; order.status = '待用户确认';
    order.proposedPrice = proposedPrice;
    order.finalPrice = proposedPrice; // Compatibility only; this is not the driver's final locked price.
    order.priceStatus = 'proposed';
  }
  if (action === 'reject') {
    operations.releaseReservation(order);
    order.reviewStatus = 'rejected'; order.status = '已驳回'; order.assignedNode = null;
    startRefund(order, note, now);
    releaseCapacity(data, order, now);
  }
  order.reviewNote = note || (action === 'approve' ? '材料已通过模拟审核。' : '模拟审核已驳回。'); order.updatedAt = now;
  order.reviewHistory.push({ action, note: order.reviewNote, node: order.assignedNode, proposedPrice: order.proposedPrice, at: now, operator: input.operator || '运营演示账号', simulated: true });
  log(data, 'OPS_ORDER_REVIEWED', input.operator || '运营演示账号', { orderId: id, action, nodeId: order.assignedNode?.id }); write(data); return { order, idempotent: false };
}

function confirmOrder(id, input = {}) {
  const data = read(), order = findOrder(data, id);
  const acceptedPrice = moneyValue(input.acceptedPrice, '用户确认金额');
  const proposedPrice = moneyValue(order.proposedPrice ?? order.finalPrice ?? order.quote?.basePrice, '运营建议价');
  if (Math.round(acceptedPrice * 100) !== Math.round(proposedPrice * 100)) throw new StoreError('运营建议价已变化，请刷新订单后重新确认金额', 409, 'PRICE_CHANGED');
  if (order.reviewStatus === 'confirmed') return { order, idempotent: true };
  if (order.reviewStatus !== 'approved') throw new StoreError('订单尚未审核通过，不能确认', 409, 'INVALID_ORDER_STATE');
  if (order.deposit?.status !== 'paid' || proposedPrice < order.deposit.amount) throw new StoreError('订单保证金或方案金额异常，暂不能确认', 409, 'INVALID_ORDER_STATE');
  operations.confirmReservation(data, order);
  const now = new Date().toISOString(); order.reviewStatus = 'confirmed'; order.status = '待拼单'; order.confirmedAt = now; order.updatedAt = now;
  order.confirmedPrice = proposedPrice; order.priceStatus = 'confirmed_proposal';
  order.reviewHistory.push({ action: 'confirm', note: '用户已确认模拟方案及运营建议价', acceptedPrice, at: now, operator: '用户演示账号', simulated: true });
  log(data, 'USER_ORDER_CONFIRMED', '用户演示账号', { orderId: id }); write(data); return { order, idempotent: false };
}

function cancelOrder(id, input = {}) {
  const data = read(), order = findOrder(data, id);
  if (order.reviewStatus === 'cancelled') return { order, idempotent: true };
  if (order.nodeReservation?.status === 'arrived') throw new StoreError('宠物已到交接点，请联系运营完成交接后处理取消', 409, 'PET_AT_NODE');
  if (order.routeId || data.routes.some((route) => route.orderIds.includes(id))) throw new StoreError('订单已编线，请联系运营处理取消', 409, 'ORDER_IN_ROUTE');
  if (!['not_submitted', 'pending', 'resubmitted', 'info_required', 'approved', 'confirmed'].includes(order.reviewStatus) || !['unpaid', 'paid'].includes(order.deposit?.status)) throw new StoreError('当前订单不可取消', 409, 'INVALID_ORDER_STATE');
  const reason = String(input.reason || '用户取消订单').trim(), now = new Date().toISOString();
  operations.releaseReservation(order);
  releaseCapacity(data, order, now);
  startRefund(order, reason, now);
  Object.assign(order, { status: '已取消', reviewStatus: 'cancelled', cancelReason: reason, cancelledAt: now, updatedAt: now, assignedNode: null });
  order.reviewHistory.push({ action: 'cancel', note: reason, at: now, operator: '用户演示账号', simulated: true });
  log(data, 'USER_ORDER_CANCELLED', '用户演示账号', { orderId: id, reason }); write(data);
  return { order, idempotent: false };
}

function rescheduleOrder(id, input = {}) {
  const data = read(), order = findOrder(data, id);
  if (order.routeId || !['not_submitted', 'pending', 'resubmitted', 'info_required'].includes(order.reviewStatus) || !['unpaid', 'paid'].includes(order.deposit?.status)) throw new StoreError('订单已通过审核或已关闭，不能直接改期，请取消后重新下单', 409, 'INVALID_ORDER_STATE');
  const slotId = required(input.slotId, '新接宠时段');
  const sameSlot = slotId === order.pickup?.slotId;
  const slot = validateSlot(data, slotId, order.fromCity, sameSlot && order.capacityHeld);
  if (sameSlot) return { order, idempotent: true };
  const now = new Date().toISOString(), previousPickup = { ...order.pickup };
  // Check the new slot before releasing the old one so failed moves never lose a reservation.
  releaseCapacity(data, order, now);
  if (order.deposit.status === 'paid') { slot.occupied += 1; order.capacityHeld = true; order.capacityReleasedAt = null; }
  order.pickup = { city: slot.city, date: slot.date, timeSlot: slot.timeSlot, slotId: slot.id };
  order.updatedAt = now;
  order.reviewHistory.push({ action: 'reschedule', note: `改期至 ${slot.date} ${slot.timeSlot}`, previousPickup, at: now, operator: '用户演示账号', simulated: true });
  log(data, 'USER_ORDER_RESCHEDULED', '用户演示账号', { orderId: id, fromSlotId: previousPickup.slotId, toSlotId: slot.id }); write(data);
  return { order, idempotent: false };
}

function processRefund(id, input = {}) {
  const data = read(), order = findOrder(data, id), outcome = input.outcome;
  const operator = String(input.operator || '运营演示账号');
  if (!['succeeded', 'failed'].includes(outcome)) throw new StoreError('退款结果仅支持 succeeded 或 failed');
  if (!['cancelled', 'rejected'].includes(order.reviewStatus)) throw new StoreError('当前订单没有可处理的退款', 409, 'INVALID_REFUND_STATE');
  if (!order.refund && ['refunding', 'refund_failed'].includes(order.deposit?.status)) {
    order.refund = { id: `RF-${id}`, status: order.deposit.status === 'refunding' ? 'pending' : 'failed', amount: order.deposit.amount, reason: order.reviewNote || order.cancelReason, requestedAt: order.updatedAt, attempts: 0, simulated: true };
  }
  if (order.refund?.status === 'succeeded') {
    if (outcome === 'failed') throw new StoreError('退款已成功，不能改为失败', 409, 'REFUND_FINISHED');
    return { order, idempotent: true, simulatedRefund: true };
  }
  if (!['pending', 'failed'].includes(order.refund?.status) || !['refunding', 'refund_failed'].includes(order.deposit?.status)) throw new StoreError('当前订单没有可处理的退款', 409, 'INVALID_REFUND_STATE');
  const now = new Date().toISOString();
  Object.assign(order.refund, { status: outcome, updatedAt: now, attempts: (order.refund.attempts || 0) + 1, failureReason: outcome === 'failed' ? String(input.reason || '模拟退款失败，请运营重试') : '' });
  if (outcome === 'succeeded') order.refund.completedAt = now;
  order.deposit.status = outcome === 'succeeded' ? 'refunded' : 'refund_failed';
  order.depositStatus = outcome === 'succeeded' ? '已退款' : '退款失败'; order.updatedAt = now;
  order.reviewHistory.push({ action: `refund_${outcome}`, note: outcome === 'succeeded' ? '模拟保证金退款已完成' : order.refund.failureReason, at: now, operator, simulated: true });
  log(data, 'OPS_REFUND_PROCESSED', operator, { orderId: id, outcome, amount: order.refund.amount }); write(data);
  return { order, idempotent: false, simulatedRefund: true };
}

function dashboard() {
  const data = read();
  const needsReviewOrRoute = (order) => ['pending', 'resubmitted'].includes(order.reviewStatus) || (order.reviewStatus === 'confirmed' && !order.routeId);
  const total = data.cityNodes.reduce((sum, node) => sum + node.capacity, 0), used = data.cityNodes.reduce((sum, node) => sum + operations.summaryNode(data, node).occupied, 0);
  return { metrics: [
    { label: '待审核/拼单', value: data.orders.filter(needsReviewOrRoute).length, note: '含已到点但尚未编线的订单' },
    { label: '进行中干线', value: data.routes.filter((route) => ['已派车', '运输中'].includes(route.status) || (['凑单中', '待发车'].includes(route.status) && Date.parse(route.departureAt) > Date.now())).length, note: '过期且未派车的历史线路不计入' },
    { label: '当前在点宠物', value: used, note: `配置总容量 ${total}；可预约量以节点日历为准` }, { label: '待处理履约异常', value: data.orders.filter((o) => o.fulfillment?.stage === 'exception').length, note: '在订单详情中核实处理，恢复原履约流程' }
  ], alert: data.orders.some(needsReviewOrRoute) ? '有待审核或待拼单订单。' : '当前没有待审核或待拼单订单。', simulated: true };
}

function listOrders(query = {}) {
  let orders = read().orders;
  if (query.status) orders = orders.filter((order) => order.status === query.status);
  if (query.city) orders = orders.filter((order) => order.fromCity === query.city || order.toCity === query.city);
  if (query.phone) orders = orders.filter((order) => order.userPhone === query.phone);
  return orders;
}
function listCityNodes() { const data = read(); return data.cityNodes.map((node) => operations.summaryNode(data, node)); }
function nodeCalendar(query = {}) { return operations.nodeCalendar(read(), query); }
function updateCityNode(id, input = {}) { const data = read(), result = operations.updateCityNode(data, id, input); write(data); return result; }
function partnerNode(identity, query = {}) { return partners.node(read(), identity, query); }
function listCapacityRequests(identity, query = {}) { return partners.list(read(), identity, query); }
function submitCapacityRequest(identity, input = {}) { const data = read(), result = partners.submit(data, identity, input); if (!result.idempotent) write(data); return result; }
function reviewCapacityRequest(id, identity, input = {}) { const data = read(), result = partners.review(data, id, identity, input); if (!result.idempotent) write(data); return result; }
function nodeCheckIn(id, input = {}) { const data = read(), result = operations.nodeCheckIn(data, findOrder(data, id), input); if (!result.idempotent) write(data); return result; }
function nodeCheckOut(id, input = {}) { const data = read(), result = operations.nodeCheckOut(data, findOrder(data, id), input); if (!result.idempotent) write(data); return result; }
function listRoutes() { const data = read(); return data.routes.map((route) => operations.routeSummary(data, route)); }
function getRoute(id) { const data = read(); return operations.routeSummary(data, operations.findRoute(data, id)); }
function createRoute(input = {}) { const data = read(), result = operations.createRoute(data, input); write(data); return result; }
function addOrderToRoute(routeId, orderId, input = {}) { const data = read(), result = operations.addOrderToRoute(data, routeId, findOrder(data, orderId), input); write(data); return result; }
function removeOrderFromRoute(routeId, orderId, input = {}) { const data = read(), result = operations.removeOrderFromRoute(data, routeId, findOrder(data, orderId), input); write(data); return result; }
function assignRoute(id, input = {}) { const data = read(), result = operations.assignRoute(data, id, input); write(data); return result; }
function dispatchRoute(id, input = {}) { const data = read(), result = operations.dispatchRoute(data, id, input); if (!result.idempotent) write(data); return result; }
function listTransportResources() { return { ...read().transportResources, simulated: true }; }
function updateOrderStatus(id, status) {
  findOrder(read(), id); required(status, '订单状态');
  throw new StoreError('请使用审核、节点到离点或线路派车操作，不能直接改写业务状态', 409, 'INVALID_STATUS_TRANSITION');
}
function resetDemo() { const data = demoData(); data.demo.resetAt = new Date().toISOString(); write(data); return { ok: true, message: '演示数据已重置', resetAt: data.demo.resetAt, simulated: true }; }

function listDriverOrders(driverId) {
  const data = read();
  const routeIds = new Set(data.routes.filter((r) => r.driverId === driverId && ['已派车', '运输中', '已完成'].includes(r.status)).map((r) => r.id));
  return data.orders.filter((o) => routeIds.has(o.routeId) && data.routes.find((r) => r.id === o.routeId)?.orderIds.includes(o.id));
}
function getDriverOrder(id, driverId) { const data = read(), order = findOrder(data, id); fulfillment.allowed(data, order, driverId); return order; }
function fulfillmentAction(action, id, input = {}) {
  if (!['inspect', 'payBalance', 'depart', 'checkpoint', 'reportException', 'resolveException', 'receive'].includes(action)) throw new StoreError('未知履约动作');
  const data = read(), result = fulfillment[action](data, findOrder(data, id), input);
  if (!result.idempotent) write(data);
  // Re-hydrate the response's transport summary after route status changes.
  result.order = getOrder(id);
  return result;
}

module.exports = { StoreError, read, write, dashboard, listOrders, addOrderToRoute, updateOrderStatus, createQuote, listAvailability, availabilityMeta, createOrder, listUserOrders, getUserOrder, getOrder, payDeposit, supplementOrder, reviewOrder, confirmOrder, cancelOrder, rescheduleOrder, processRefund, resetDemo, demoData, listCityNodes, nodeCalendar, updateCityNode, nodeCheckIn, nodeCheckOut, listRoutes, getRoute, createRoute, removeOrderFromRoute, assignRoute, dispatchRoute, listTransportResources };
Object.assign(module.exports, { listDriverOrders, getDriverOrder, fulfillmentAction });
Object.assign(module.exports, { partnerNode, listCapacityRequests, submitCapacityRequest, reviewCapacityRequest });

},
"./operations": function(module, exports, require) {
// Pure, synchronous business operations. The store persists only after a complete action succeeds.
module.exports = function operations({ StoreError, shanghaiDate, addDays, log }) {
  const periods = [{ id: 'AM', timeSlot: '09:00-12:00' }, { id: 'PM', timeSlot: '13:00-16:00' }];
  const active = ['reserved', 'confirmed', 'arrived'];
  const fail = (message, code = 'INVALID_OPERATION', status = 409) => { throw new StoreError(message, status, code); };
  const now = () => new Date().toISOString();
  const operator = (input) => String(input?.operator || '运营演示账号');
  function validDate(value) {
    if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value) || !Number.isFinite(Date.parse(`${value}T00:00:00Z`)) || new Date(`${value}T00:00:00Z`).toISOString().slice(0, 10) !== value) fail('日期格式不正确', 'INVALID_DATE', 400);
    return value;
  }
  function integer(value, label, min = 1, max = 100) {
    if (value === '' || value == null || typeof value === 'boolean' || !Number.isInteger(Number(value)) || Number(value) < min || Number(value) > max) fail(`${label}需为 ${min}-${max} 之间的整数`, 'INVALID_CONFIGURATION', 400);
    return Number(value);
  }
  function timestamp(value, label) {
    if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}T([01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d{1,3})?)?(Z|[+-]\d{2}:\d{2})$/.test(value) || !Number.isFinite(Date.parse(value))) fail(`${label}需为带时区的有效日期时间`, 'INVALID_TIME', 400);
    validDate(value.slice(0, 10));
    return new Date(value).toISOString();
  }
  function openHours(value) {
    if (typeof value !== 'string' || !/^([01]\d|2[0-3]):[0-5]\d-([01]\d|2[0-3]):[0-5]\d$/.test(value) || value.slice(0, 5) >= value.slice(6)) fail('营业时间需为同一天内的有效时间段，例如 09:00-20:00', 'INVALID_OPEN_HOURS', 400);
    return value;
  }
  function configFields(input) {
    const out = {};
    if ('capacity' in input) out.capacity = integer(input.capacity, '节点容量');
    if ('periodCapacities' in input) {
      const values = input.periodCapacities;
      if (!values || typeof values !== 'object' || Array.isArray(values) || Object.keys(values).sort().join(',') !== 'AM,PM') fail('请同时填写上午和下午总笼位', 'INVALID_CONFIGURATION', 400);
      out.periodCapacities = { AM: integer(values.AM, '上午总笼位', 0), PM: integer(values.PM, '下午总笼位', 0) };
    }
    if ('open' in input) out.open = openHours(input.open);
    if ('status' in input) { if (!['正常', '暂停'].includes(input.status)) fail('节点状态仅支持正常或暂停', 'INVALID_NODE_STATUS', 400); out.status = input.status; }
    return out;
  }
  function findNode(data, id) { const node = data.cityNodes.find((n) => n.id === id); if (!node) fail('未找到交接节点', 'NODE_NOT_FOUND', 404); return node; }
  function findRoute(data, id) { const route = data.routes.find((r) => r.id === id); if (!route) fail('未找到线路', 'ROUTE_NOT_FOUND', 404); return route; }
  function periodOf(order) { return periods.find((p) => p.timeSlot === order.pickup?.timeSlot)?.id; }
  function slotTime(date, period, end = false) {
    const p = periods.find((p) => p.id === period);
    if (!p) fail('节点时段仅支持 AM 或 PM', 'INVALID_NODE_PERIOD', 400);
    return `${validDate(date)}T${p.timeSlot.split('-')[end ? 1 : 0]}:00+08:00`;
  }
  function configuration(node, date, period) {
    const cfg = { capacity: node.capacity, open: node.open, status: node.status, ...(node.dateOverrides || []).find((v) => v.date === date) };
    if (period && cfg.periodCapacities) cfg.capacity = cfg.periodCapacities[period];
    return cfg;
  }
  function consumes(reservation, date, period) {
    if (!reservation || !active.includes(reservation.status)) return false;
    if (reservation.status === 'arrived') return `${reservation.date}-${reservation.period}` <= `${date}-${period}`;
    return reservation.date === date && reservation.period === period;
  }
  function cell(data, node, date, period, exceptId) {
    const cfg = configuration(node, date, period), window = periods.find((p) => p.id === period);
    const orders = data.orders.filter((o) => o.id !== exceptId && o.nodeReservation?.nodeId === node.id && consumes(o.nodeReservation, date, period));
    const reserved = orders.filter((o) => o.nodeReservation.status === 'reserved').length;
    const confirmed = orders.filter((o) => o.nodeReservation.status === 'confirmed').length;
    const arrived = orders.filter((o) => o.nodeReservation.status === 'arrived').length;
    const matchesHours = cfg.open.slice(0, 5) <= window.timeSlot.slice(0, 5) && cfg.open.slice(6) >= window.timeSlot.slice(6);
    const expired = Date.parse(slotTime(date, period, true)) <= Date.now();
    const occupied = reserved + confirmed + arrived, remaining = Math.max(0, cfg.capacity - occupied);
    const blockedReason = expired ? '该预约窗口已结束，不可再预约' : cfg.status !== '正常' ? '节点已暂停预约' : !matchesHours ? '预约窗口不在营业时间内' : occupied > cfg.capacity ? '在点宠物跨窗占用，请先完成离点交接后再接收本窗预约' : !remaining ? '该窗口笼位已满' : '';
    return { nodeId: node.id, nodeName: node.name, city: node.city, date, period, timeSlot: window.timeSlot, ...cfg, reserved, confirmed, arrived, occupied, remaining, expired, available: !blockedReason, blockedReason, orderIds: orders.map((o) => o.id) };
  }
  function assertCell(data, node, date, period, exceptId) {
    const value = cell(data, node, date, period, exceptId);
    if (!value.available) fail(value.blockedReason, value.expired ? 'NODE_RESERVATION_EXPIRED' : value.status !== '正常' ? 'NODE_PAUSED' : value.remaining === 0 ? 'NODE_FULL' : 'NODE_TIME_MISMATCH');
    return value;
  }
  function summaryNode(data, node) {
    return { ...node, occupied: data.orders.filter((o) => o.nodeReservation?.nodeId === node.id && o.nodeReservation.status === 'arrived').length, simulated: true };
  }
  function hydrate(data) {
    data.cityNodes ||= []; data.routes ||= []; data.orders ||= [];
    for (const node of data.cityNodes) { node.dateOverrides ||= []; node.open ||= '09:00-20:00'; node.status ||= '正常'; node.configVersion ||= 0; }
    data.transportResources ||= {
      drivers: [{ id: 'DRV-001', name: '刘师傅', phone: '13800001001', status: '可用' }, { id: 'DRV-002', name: '陈师傅', phone: '13800001002', status: '可用' }, { id: 'DRV-003', name: '王师傅', phone: '13800001003', status: '可用' }],
      vehicles: [{ id: 'VEH-001', plate: '粤A·PC001', capacity: 8, status: '可用' }, { id: 'VEH-002', plate: '粤A·PC002', capacity: 6, status: '可用' }, { id: 'VEH-003', plate: '鄂A·PC003', capacity: 8, status: '可用' }]
    };
    for (const route of data.routes) { route.orderIds ||= []; route.cities ||= (route.nodes || []).map((n) => n.city); }
    for (const order of data.orders) if (order.routeId) {
      const route = data.routes.find((r) => r.id === order.routeId);
      if (route) order.transport = transport(route);
    }
    return data;
  }
  function nodeCalendar(data, query = {}) {
    const date = validDate(query.date || shanghaiDate()), days = integer(query.days ?? 7, '日历天数', 1, 31);
    const nodes = query.nodeId ? [findNode(data, query.nodeId)] : data.cityNodes;
    const items = [];
    for (let offset = 0; offset < days; offset += 1) for (const node of nodes) for (const p of periods) items.push(cell(data, node, addDays(date, offset), p.id));
    return { date, days, periods, items, simulated: true };
  }
  function validateConfiguration(data, node) {
    const dates = new Set([shanghaiDate(), ...(node.dateOverrides || []).map((v) => v.date)]);
    for (const o of data.orders) if (o.nodeReservation?.nodeId === node.id && active.includes(o.nodeReservation.status)) dates.add(o.nodeReservation.date);
    // Include future windows so a currently boarded pet cannot be hidden by changing a date override.
    for (let offset = 1; offset <= 31; offset += 1) dates.add(addDays(shanghaiDate(), offset));
    for (const date of dates) for (const p of periods) {
      const c = cell(data, node, date, p.id);
      if (c.occupied > c.capacity || (c.occupied > 0 && (c.status !== '正常' || c.open.slice(0, 5) > c.timeSlot.slice(0, 5) || c.open.slice(6) < c.timeSlot.slice(6)))) fail(`${date} ${p.id} 有 ${c.occupied} 个已预约或在点笼位，当前配置会与其冲突`, 'NODE_CONFIGURATION_CONFLICT');
    }
  }
  function updateCityNode(data, id, input = {}) {
    if ('periodCapacities' in input) fail('分时容量仅可按日期设置', 'INVALID_CONFIGURATION', 400);
    const node = findNode(data, id); Object.assign(node, configFields(input));
    if (input.override) {
      const date = validDate(input.override.date);
      if (date < shanghaiDate()) fail('不能修改过去日期的节点配置', 'DATE_EXPIRED');
      const fields = configFields(input.override), previous = node.dateOverrides.find((v) => v.date === date);
      if (!Object.keys(fields).length) fail('请至少设置一项日期覆盖配置', 'EMPTY_CONFIGURATION', 400);
      // An explicit whole-day capacity replaces an earlier partner AM/PM split.
      if (previous) { if ('capacity' in fields && !('periodCapacities' in fields)) delete previous.periodCapacities; Object.assign(previous, fields); }
      else node.dateOverrides.push({ date, ...fields });
    }
    if (input.removeOverrideDate) node.dateOverrides = node.dateOverrides.filter((v) => v.date !== validDate(input.removeOverrideDate));
    validateConfiguration(data, node); node.updatedAt = now(); node.configVersion = (node.configVersion || 0) + 1;
    log(data, 'NODE_CONFIGURATION_UPDATED', operator(input), { nodeId: id, capacity: node.capacity, open: node.open, status: node.status, dateOverrides: node.dateOverrides });
    return { node: summaryNode(data, node) };
  }
  function reserve(data, order, input = {}) {
    if (!order.pickup?.date || !periodOf(order)) fail('订单缺少有效接宠预约，请补齐后重新审核', 'PICKUP_REQUIRED');
    const date = validDate(input.nodeDate || order.pickup.date), period = input.nodePeriod || periodOf(order);
    if (date < shanghaiDate() || date !== order.pickup.date || period !== periodOf(order)) fail('交接节点预约必须与订单接宠日期和时段一致', 'NODE_TIME_MISMATCH');
    let nodes = data.cityNodes.filter((n) => n.city === order.fromCity);
    if (input.nodeId) nodes = [findNode(data, input.nodeId)];
    if (nodes.some((n) => n.city !== order.fromCity)) fail('交接节点与出发城市不匹配', 'NODE_CITY_MISMATCH');
    const node = input.nodeId ? nodes[0] : nodes.find((n) => cell(data, n, date, period, order.id).available);
    if (!node) fail('出发城市该窗口暂无可预约节点', 'NODE_UNAVAILABLE');
    assertCell(data, node, date, period, order.id);
    order.assignedNode = { id: node.id, city: node.city, name: node.name, open: configuration(node, date).open };
    order.nodeReservation = { nodeId: node.id, date, period, timeSlot: periods.find((p) => p.id === period).timeSlot, status: 'reserved', reservedAt: now() };
  }
  function confirmReservation(data, order) {
    const r = order.nodeReservation;
    if (!r || r.status !== 'reserved') fail('节点预留不存在，请联系运营重新审核', 'NODE_RESERVATION_REQUIRED');
    if (Date.parse(slotTime(r.date, r.period, true)) <= Date.now()) fail('节点预约已过期，请联系运营处理', 'NODE_RESERVATION_EXPIRED');
    const cfg = configuration(findNode(data, r.nodeId), r.date, r.period), window = periods.find((p) => p.id === r.period);
    if (cfg.status !== '正常') fail('节点已暂停预约，请联系运营处理', 'NODE_PAUSED');
    if (cfg.open.slice(0, 5) > window.timeSlot.slice(0, 5) || cfg.open.slice(6) < window.timeSlot.slice(6)) fail('预约窗口不在营业时间内', 'NODE_TIME_MISMATCH');
    const scheduled = data.orders.filter((o) => o.nodeReservation?.nodeId === r.nodeId && o.nodeReservation.date === r.date && o.nodeReservation.period === r.period && active.includes(o.nodeReservation.status)).length;
    if (scheduled > cfg.capacity) fail('本窗口预留超过节点配置容量，请联系运营处理', 'NODE_FULL');
    // Confirmation changes the state of an already held position. Earlier boarded pets
    // can block new bookings and physical admission, but cannot take away this prior hold.
    r.status = 'confirmed'; r.confirmedAt = now();
  }
  function releaseReservation(order) {
    const r = order.nodeReservation;
    if (!r || ['released', 'departed'].includes(r.status)) return;
    if (r.status === 'arrived') fail('宠物已到交接点，须由运营完成交接后再处理订单', 'PET_AT_NODE');
    r.status = 'released'; r.releasedAt = now();
  }
  function history(data, order, action, note, input) {
    order.updatedAt = now(); order.reviewHistory ||= [];
    order.reviewHistory.push({ action, note, at: order.updatedAt, operator: operator(input), simulated: true });
    log(data, action.toUpperCase(), operator(input), { orderId: order.id, nodeId: order.nodeReservation?.nodeId, routeId: order.routeId, note });
  }
  function nodeCheckIn(data, order, input = {}) {
    const r = order.nodeReservation;
    if (r?.status === 'arrived') return { order, idempotent: true, simulated: true };
    if (order.reviewStatus !== 'confirmed' || order.deposit?.status !== 'paid' || r?.status !== 'confirmed') fail('仅已确认方案且预约生效的订单可办理到点', 'NODE_CHECKIN_NOT_ALLOWED');
    const occurredAt = timestamp(input.occurredAt || slotTime(r.date, r.period), '到点时间');
    if (Date.parse(occurredAt) < Date.parse(slotTime(r.date, r.period)) || Date.parse(occurredAt) > Date.parse(slotTime(r.date, r.period, true))) fail('到点时间必须处于预约窗口内', 'NODE_TIME_MISMATCH');
    const node = findNode(data, r.nodeId);
    assertCell(data, node, r.date, r.period, order.id);
    const physicallyPresent = data.orders.filter((o) => o.id !== order.id && o.nodeReservation?.nodeId === r.nodeId && o.nodeReservation.status === 'arrived').length;
    if (physicallyPresent >= configuration(node, r.date, r.period).capacity) fail('节点当前实在点笼位已满，请先办理离点交接', 'NODE_FULL');
    r.status = 'arrived'; r.checkedInAt = occurredAt; r.checkInRecordedAt = now();
    // Future reservations must not prevent today's arrival. Until this pet is explicitly
    // handed out, later calendar windows include it, warn on overlap, and block new bookings.
    order.status = order.routeId ? '节点待发车' : '已到交接点';
    history(data, order, 'node_checkin', String(input.note || '模拟到点，宠物已进入交接点'), input);
    return { order, idempotent: false, simulated: true };
  }
  function routeEditable(route) {
    if (!['凑单中', '待发车'].includes(route.status)) return '线路已派车或关闭，不能修改编线';
    if (!route.departureAt || Date.parse(route.departureAt) <= Date.now()) return '线路发车时间已过期，请新建未来线路';
    if (!route.arrivalAt || !Number.isFinite(Date.parse(route.arrivalAt)) || Date.parse(route.arrivalAt) <= Date.parse(route.departureAt)) return '历史线路缺少有效到达时间，请新建线路';
    return '';
  }
  function assertEditable(route) { const message = routeEditable(route); if (message) fail(message, 'ROUTE_NOT_EDITABLE'); }
  function segments(data, route, extraOrder) {
    const orders = route.orderIds.map((id) => data.orders.find((o) => o.id === id)).filter(Boolean);
    if (extraOrder) orders.push(extraOrder);
    return route.cities.slice(0, -1).map((fromCity, index) => {
      const used = orders.filter((o) => route.cities.indexOf(o.fromCity) <= index && route.cities.indexOf(o.toCity) > index).length;
      return { fromCity, toCity: route.cities[index + 1], capacity: route.capacity, used, remaining: route.capacity - used };
    });
  }
  function routeSummary(data, route) {
    const routeSegments = segments(data, route);
    let dispatchBlockedReason = routeEditable(route);
    if (!dispatchBlockedReason) {
      try {
        if (route.orderIds.length < route.minOrders) fail(`尚未达到最小发车 ${route.minOrders} 单`, 'MIN_ORDERS_NOT_MET');
        resourcesFor(data, route, route.driverId, route.vehicleId);
        for (const orderId of route.orderIds) {
          const order = data.orders.find((o) => o.id === orderId);
          if (!order || order.routeId !== route.id || order.deposit?.status !== 'paid' || order.reviewStatus !== 'confirmed') fail('线路含无效订单，请重新核查编线', 'INVALID_ROUTE_ORDER');
          validateOrderTiming(order, route);
        }
        if (routeSegments.some((s) => s.used > s.capacity)) fail('线路区段超量，不能派车', 'ROUTE_FULL');
      } catch (error) { if (!(error instanceof StoreError)) throw error; dispatchBlockedReason = error.message; }
    }
    return { ...route, segments: routeSegments, nodes: route.cities.map((city, index) => ({ city, capacity: route.capacity, used: routeSegments[index]?.used || 0 })), canEdit: !routeEditable(route), blockedReason: routeEditable(route), canDispatch: !dispatchBlockedReason, dispatchBlockedReason, simulated: true };
  }
  function transport(route) { return { routeId: route.id, routeName: route.name, cities: [...route.cities], departureAt: route.departureAt, arrivalAt: route.arrivalAt || null, driverName: route.driverName || route.driver || '', vehiclePlate: route.vehiclePlate || '', routeStatus: route.status, dispatchedAt: route.dispatchedAt || null, simulated: true }; }
  function syncOrders(data, route) { for (const id of route.orderIds) { const o = data.orders.find((o) => o.id === id); if (o) o.transport = transport(route); } }
  function createRoute(data, input = {}) {
    const cities = input.cities;
    if (!Array.isArray(cities) || cities.length < 2 || cities.length > 12 || cities.some((c) => typeof c !== 'string' || !data.cityNodes.some((n) => n.city === c)) || new Set(cities).size !== cities.length) fail('请按顺序选择至少两个不重复且已有交接点的城市', 'INVALID_ROUTE_CITIES', 400);
    const departureAt = timestamp(input.departureAt, '发车时间'), arrivalAt = timestamp(input.arrivalAt, '预计到达时间');
    if (Date.parse(departureAt) <= Date.now() || Date.parse(arrivalAt) <= Date.parse(departureAt) || Date.parse(arrivalAt) - Date.parse(departureAt) > 14 * 86400000) fail('线路须在未来发车、晚于发车到达，行程不超过 14 天', 'INVALID_ROUTE_TIME', 400);
    const capacity = integer(input.capacity ?? 8, '线路容量'), minOrders = integer(input.minOrders ?? 1, '最小发车单数'), maxWaitingHours = integer(input.maxWaitingHours ?? 36, '最大等待小时', 1, 168);
    // A route can reuse seats over non-overlapping segments, so minOrders may exceed its seat capacity.
    const route = { id: `LINE-${Date.now()}-${Math.random().toString(16).slice(2, 6).toUpperCase()}`, name: String(input.name || cities.join('—')).trim(), cities: [...cities], departureAt, arrivalAt, capacity, minOrders, maxWaitingHours, status: '凑单中', orderIds: [], nodes: cities.map((city) => ({ city, capacity, used: 0 })), createdAt: now(), createdBy: operator(input), driverId: '', vehicleId: '', driverName: '', vehiclePlate: '' };
    data.routes.unshift(route); log(data, 'ROUTE_CREATED', operator(input), { routeId: route.id, cities, departureAt, arrivalAt });
    return { route: routeSummary(data, route) };
  }
  function validateOrderTiming(order, route) {
    const r = order.nodeReservation;
    if (!order.pickup?.date || !order.assignedNode || !r || !['confirmed', 'arrived'].includes(r.status)) fail('订单缺少已确认的接宠/交接点预约，不能编线', 'NODE_RESERVATION_REQUIRED');
    if (r.date !== order.pickup.date || r.period !== periodOf(order)) fail('订单接宠与节点预约时间不一致', 'NODE_TIME_MISMATCH');
    const readyAt = Date.parse(slotTime(r.date, r.period, true)), beginsAt = Date.parse(slotTime(r.date, r.period)), departure = Date.parse(route.departureAt);
    if (r.status !== 'arrived' && readyAt <= Date.now()) fail('节点预约窗口已结束且尚未到点，请先处理预约后再编线或派车', 'NODE_RESERVATION_EXPIRED');
    if (departure < readyAt || departure - beginsAt > route.maxWaitingHours * 3600000) fail('发车时间必须在接宠/节点窗口结束之后，且不超过线路最大等待时长', 'ROUTE_PICKUP_TIME_MISMATCH');
  }
  function addOrderToRoute(data, routeId, order, input = {}) {
    const route = findRoute(data, routeId);
    if (order.routeId || data.routes.some((r) => r.orderIds.includes(order.id))) fail('该订单已加入线路，不能重复编线', 'ALREADY_IN_ROUTE');
    if (order.deposit?.status !== 'paid' || order.reviewStatus !== 'confirmed' || !['待拼单', '已到交接点'].includes(order.status)) fail('订单需支付保证金、通过审核并由用户确认方案后才能编线', 'INVALID_ORDER_STATE');
    assertEditable(route); validateOrderTiming(order, route);
    const from = route.cities.indexOf(order.fromCity), to = route.cities.indexOf(order.toCity);
    if (from < 0 || to <= from) fail('订单不在当前干线的顺向连续路段内', 'ROUTE_DIRECTION_MISMATCH');
    if (segments(data, route, order).some((s) => s.used > s.capacity)) fail('所经路段笼位已满', 'ROUTE_FULL');
    route.orderIds.push(order.id); order.routeId = routeId; order.status = order.nodeReservation.status === 'arrived' ? '节点待发车' : '已编入干线';
    route.status = route.orderIds.length >= route.minOrders ? '待发车' : '凑单中'; syncOrders(data, route);
    history(data, order, 'order_added_to_route', `编入 ${route.name}`, input);
    return { route: routeSummary(data, route), order };
  }
  function removeOrderFromRoute(data, routeId, order, input = {}) {
    const route = findRoute(data, routeId); assertEditable(route);
    if (order.routeId !== routeId || !route.orderIds.includes(order.id)) fail('订单不在该线路中', 'ORDER_NOT_IN_ROUTE');
    route.orderIds = route.orderIds.filter((id) => id !== order.id); order.routeId = ''; order.transport = null;
    order.status = order.nodeReservation?.status === 'arrived' ? '已到交接点' : '待拼单';
    route.status = route.orderIds.length >= route.minOrders ? '待发车' : '凑单中'; syncOrders(data, route);
    history(data, order, 'order_removed_from_route', `移出 ${route.name}，节点预约保留`, input);
    return { route: routeSummary(data, route), order };
  }
  function resourcesFor(data, route, driverId, vehicleId) {
    const driver = data.transportResources.drivers.find((d) => d.id === driverId), vehicle = data.transportResources.vehicles.find((v) => v.id === vehicleId);
    if (!driver || !vehicle || driver.status !== '可用' || vehicle.status !== '可用') fail('请选择可用的虚拟司机和车辆', 'RESOURCE_UNAVAILABLE');
    if (vehicle.capacity < route.capacity) fail('车辆笼位少于线路设定容量，请选择更大车辆', 'VEHICLE_CAPACITY_TOO_SMALL');
    const conflict = data.routes.find((r) => r.id !== route.id && !['已完成', '已取消'].includes(r.status) && r.arrivalAt && Date.parse(r.departureAt) < Date.parse(route.arrivalAt) && Date.parse(route.departureAt) < Date.parse(r.arrivalAt) && (r.driverId === driver.id || r.vehicleId === vehicle.id));
    if (conflict) fail(`司机或车辆与线路「${conflict.name}」的运输时间冲突`, 'RESOURCE_TIME_CONFLICT');
    return { driver, vehicle };
  }
  function assignRoute(data, id, input = {}) {
    const route = findRoute(data, id); assertEditable(route);
    if (input.driverId === '' && input.vehicleId === '') {
      Object.assign(route, { driverId: '', driverName: '', driver: '', vehicleId: '', vehiclePlate: '', assignedAt: null });
      syncOrders(data, route); log(data, 'ROUTE_RESOURCE_RELEASED', operator(input), { routeId: id });
      return { route: routeSummary(data, route) };
    }
    const { driver, vehicle } = resourcesFor(data, route, input.driverId, input.vehicleId);
    Object.assign(route, { driverId: driver.id, driverName: driver.name, driver: driver.name, vehicleId: vehicle.id, vehiclePlate: vehicle.plate, assignedAt: now() });
    syncOrders(data, route); log(data, 'ROUTE_RESOURCE_ASSIGNED', operator(input), { routeId: id, driverId: driver.id, vehicleId: vehicle.id });
    return { route: routeSummary(data, route) };
  }
  function dispatchRoute(data, id, input = {}) {
    const route = findRoute(data, id);
    if (['已派车', '运输中'].includes(route.status)) return { route: routeSummary(data, route), idempotent: true };
    assertEditable(route);
    if (route.orderIds.length < route.minOrders) fail(`尚未达到最小发车 ${route.minOrders} 单`, 'MIN_ORDERS_NOT_MET');
    resourcesFor(data, route, route.driverId, route.vehicleId);
    for (const orderId of route.orderIds) {
      const order = data.orders.find((o) => o.id === orderId);
      if (!order || order.routeId !== id || order.deposit?.status !== 'paid' || order.reviewStatus !== 'confirmed') fail('线路含无效订单，请重新核查编线', 'INVALID_ROUTE_ORDER');
      validateOrderTiming(order, route);
    }
    if (segments(data, route).some((s) => s.used > s.capacity)) fail('线路区段超量，不能派车', 'ROUTE_FULL');
    route.status = '已派车'; route.dispatchedAt = now();
    for (const orderId of route.orderIds) { const order = data.orders.find((o) => o.id === orderId); order.status = order.nodeReservation.status === 'arrived' ? '节点待发车' : '待接宠'; history(data, order, 'route_dispatched', `已安排 ${route.driverName} / ${route.vehiclePlate}`, input); }
    syncOrders(data, route); log(data, 'ROUTE_DISPATCHED', operator(input), { routeId: id });
    return { route: routeSummary(data, route), idempotent: false };
  }
  function nodeCheckOut(data, order, input = {}) {
    const r = order.nodeReservation;
    if (r?.status === 'departed') return { order, idempotent: true, simulated: true };
    if (r?.status !== 'arrived' || !order.routeId) fail('宠物须先到点并编入已派车线路，才能离点', 'NODE_CHECKOUT_NOT_ALLOWED');
    const route = findRoute(data, order.routeId);
    if (!['已派车', '运输中'].includes(route.status) || !route.orderIds.includes(order.id)) fail('线路尚未派车，不能办理离点', 'ROUTE_NOT_DISPATCHED');
    if (order.fulfillment?.invoice?.status !== 'paid' || order.fulfillment.stage !== 'ready') fail('请先由司机验宠、用户确认总价并完成模拟尾款，再办理离点', 'BALANCE_REQUIRED');
    const occurredAt = timestamp(input.occurredAt || route.departureAt, '离点时间');
    if (Date.parse(occurredAt) < Date.parse(r.checkedInAt) || Date.parse(occurredAt) < Date.parse(route.departureAt) || Date.parse(occurredAt) > Date.parse(route.arrivalAt)) fail('离点时间须在到点之后，且处于线路发车至预计到达之间', 'INVALID_CHECKOUT_TIME');
    r.status = 'departed'; r.checkedOutAt = occurredAt; r.checkOutRecordedAt = now(); order.status = '待司机出发';
    history(data, order, 'node_checkout', String(input.note || '模拟离点，节点笼位已释放，等待司机确认出发'), input);
    // A handoff is not departure: driver inspection and user balance confirmation come next.
    syncOrders(data, route); return { order, route: routeSummary(data, route), idempotent: false, simulated: true };
  }
  return { hydrate, summaryNode, nodeCalendar, updateCityNode, reserve, confirmReservation, releaseReservation, nodeCheckIn, nodeCheckOut, routeSummary, createRoute, addOrderToRoute, removeOrderFromRoute, assignRoute, dispatchRoute, findRoute };
};

},
"./partners": function(module, exports, require) {
// Partner identity comes only from the authenticated server session, never request fields.
// Each store action is synchronous: baseline validation and capacity updates commit together.
module.exports = function partners({ StoreError, operations, shanghaiDate, addDays, log }) {
  const fail = (message, code, status = 409) => { throw new StoreError(message, status, code); };
  function hydrate(data) { data.capacityRequests ||= []; return data; }
  function nodeFor(data, nodeId) {
    const node = data.cityNodes.find((item) => item.id === nodeId);
    if (!node) fail('机构未绑定有效合作节点，请联系总部', 'PARTNER_NODE_NOT_FOUND', 404);
    return node;
  }
  function dates() { const today = shanghaiDate(); return { minDate: addDays(today, 1), maxDate: addDays(today, 31) }; }
  function noteOf(value, required = false) {
    if (value != null && typeof value !== 'string') fail('说明须为文本', 'INVALID_NOTE', 400);
    const note = (value || '').trim();
    if (required && !note) fail('退回申请必须填写原因', 'REVIEW_NOTE_REQUIRED', 400);
    if (note.length > 200) fail('说明不能超过200字', 'INVALID_NOTE', 400);
    return note;
  }
  function publicCalendar(data, nodeId, query = {}) {
    const calendar = operations.nodeCalendar(data, { date: query.date, days: query.days, nodeId });
    calendar.items = calendar.items.map(({ orderIds, ...item }) => item);
    return calendar;
  }
  function summary(data, request) {
    const node = nodeFor(data, request.nodeId), current = {};
    for (const item of publicCalendar(data, node.id, { date: request.date, days: 1 }).items) {
      current[item.period] = { capacity: item.capacity, occupied: item.occupied, remaining: item.remaining };
    }
    return { ...request, currentVersion: node.configVersion || 0, isStale: request.status === 'pending' && request.baselineVersion !== (node.configVersion || 0), current, simulated: true };
  }
  function node(data, identity, query = {}) {
    const value = nodeFor(data, identity.nodeId);
    return { node: operations.summaryNode(data, value), calendar: publicCalendar(data, value.id, query), ...dates(), simulated: true };
  }
  function list(data, identity, query = {}) {
    hydrate(data);
    if (identity) nodeFor(data, identity.nodeId);
    if (query.status && !['pending', 'approved', 'returned'].includes(query.status)) fail('未知申请状态', 'INVALID_REQUEST_STATUS', 400);
    return data.capacityRequests.filter((request) => (!identity || (request.nodeId === identity.nodeId && request.submittedBy === identity.account)) && (!query.status || request.status === query.status)).map((request) => summary(data, request));
  }
  function submit(data, identity, input = {}) {
    hydrate(data);
    const value = nodeFor(data, identity.nodeId), requestId = input.requestId;
    if (typeof requestId !== 'string' || !/^[a-zA-Z0-9_.:-]{8,128}$/.test(requestId)) fail('请提供有效的防重复提交编号', 'INVALID_REQUEST_ID', 400);
    const c = input.capacities;
    if (!c || typeof c !== 'object' || Array.isArray(c) || Object.keys(c).sort().join(',') !== 'AM,PM' || ['AM', 'PM'].some((p) => !Number.isInteger(c[p]) || c[p] < 0 || c[p] > 100)) fail('上午和下午总笼位须为0到100的整数', 'INVALID_CAPACITIES', 400);
    const date = input.date, capacities = { AM: c.AM, PM: c.PM }, note = noteOf(input.note);
    const existing = data.capacityRequests.find((request) => request.submittedBy === identity.account && request.requestId === requestId);
    if (existing) {
      if (existing.nodeId !== identity.nodeId || existing.date !== date || JSON.stringify(existing.capacities) !== JSON.stringify(capacities) || existing.note !== note) fail('同一提交编号的内容已变更，请刷新后重新提交', 'REQUEST_ID_CONFLICT');
      return { request: summary(data, existing), idempotent: true, simulated: true };
    }
    // nodeCalendar performs strict calendar-date validation before any persistence.
    operations.nodeCalendar(data, { nodeId: value.id, date, days: 1 });
    const range = dates();
    if (typeof date !== 'string' || date < range.minDate || date > range.maxDate) fail('请选择明天至未来31天内的日期', 'REQUEST_DATE_OUT_OF_RANGE', 400);
    if (data.capacityRequests.some((request) => request.nodeId === value.id && request.date === date && request.status === 'pending')) fail('该节点当天已有待审核申报，请等待总部处理后再提交', 'CAPACITY_REQUEST_PENDING');
    const request = {
      id: `CAP-${Date.now()}-${require('node:crypto').randomBytes(6).toString('hex')}`, requestId,
      nodeId: value.id, nodeName: value.name, date, capacities, note, baselineVersion: value.configVersion || 0,
      status: 'pending', submittedBy: identity.account, submittedAt: new Date().toISOString(), simulated: true
    };
    data.capacityRequests.unshift(request);
    log(data, 'PARTNER_CAPACITY_SUBMITTED', identity.account, { requestId: request.id, nodeId: value.id, date, capacities });
    return { request: summary(data, request), idempotent: false, simulated: true };
  }
  function review(data, id, identity, input = {}) {
    hydrate(data);
    const request = data.capacityRequests.find((item) => item.id === id);
    if (!request) fail('未找到容量申请', 'CAPACITY_REQUEST_NOT_FOUND', 404);
    if (!['approve', 'return'].includes(input.action)) fail('审核动作仅支持通过或退回', 'INVALID_REVIEW_ACTION', 400);
    const note = noteOf(input.note, input.action === 'return'), status = input.action === 'approve' ? 'approved' : 'returned';
    if (request.status !== 'pending') {
      if (request.status === status && request.reviewNote === note && request.reviewedBy === identity.account) return { request: summary(data, request), idempotent: true, simulated: true };
      fail('申请已审核，不能覆盖原审核结果', 'CAPACITY_REQUEST_FINISHED');
    }
    const value = nodeFor(data, request.nodeId);
    let updated;
    if (input.action === 'approve') {
      if (request.date < dates().minDate) fail('申请日期已临近或过期，请退回后重新申报未来日期', 'CAPACITY_REQUEST_EXPIRED');
      if (request.baselineVersion !== (value.configVersion || 0)) fail('申报后节点配置已变更，请退回申请并让机构重新申报，避免覆盖更新', 'CAPACITY_BASELINE_STALE');
      // Rechecks existing reservations, confirmations, boarded pets and future carry-over.
      updated = operations.updateCityNode(data, value.id, { override: { date: request.date, periodCapacities: request.capacities }, operator: identity.account });
    }
    Object.assign(request, { status, reviewNote: note, reviewedBy: identity.account, reviewedAt: new Date().toISOString() });
    if (updated) request.appliedVersion = updated.node.configVersion;
    log(data, 'PARTNER_CAPACITY_REVIEWED', identity.account, { requestId: request.id, nodeId: value.id, action: input.action, note });
    return { request: summary(data, request), ...(updated ? { node: updated.node } : {}), idempotent: false, simulated: true };
  }
  return { hydrate, node, list, submit, review };
};

},
"./fulfillment": function(module, exports, require) {
const { randomUUID } = require('node:crypto');
// Virtual fulfillment only. All mutations are synchronous; the store writes after success.
module.exports = function fulfillment({ StoreError, moneyValue, log }) {
  const fail = (message, code = 'FULFILLMENT_CONFLICT', status = 409) => { throw new StoreError(message, status, code); };
  const text = (value, label, max = 300) => {
    if (typeof value !== 'string' || !value.trim() || value.trim().length > max) fail(`请填写${label}（最多 ${max} 字）`, 'INVALID_INPUT', 400);
    return value.trim();
  };
  function routeFor(data, order) { return data.routes.find((r) => r.id === order.routeId && r.orderIds.includes(order.id)); }
  function allowed(data, order, driverId) {
    const route = routeFor(data, order);
    if (!driverId || !route || route.driverId !== driverId || !['已派车', '运输中', '已完成'].includes(route.status)) fail('未找到分配给当前司机的任务', 'DRIVER_ORDER_NOT_FOUND', 404);
    return route;
  }
  function event(data, order, type, label, input = {}) {
    const at = new Date().toISOString(), flow = order.fulfillment;
    const transportEvent = ['depart', 'checkpoint', 'receipt'].includes(type);
    flow.events.push({ id: `${order.id}-${flow.events.length + 1}`, type, label, note: typeof input.note === 'string' ? input.note : '', city: transportEvent ? input.city : '', occurredAt: transportEvent ? input.occurredAt : at, recordedAt: at, operator: input.operator, simulated: true });
    order.updatedAt = at;
    const saved = flow.events[flow.events.length - 1];
    log(data, `FULFILLMENT_${type.toUpperCase()}`, input.operator, { orderId: order.id, routeId: order.routeId, note: saved.note, city: saved.city });
  }
  function activeFlow(order) {
    const flow = order.fulfillment;
    if (!flow) fail('请先完成司机验宠与费用确认', 'INSPECTION_REQUIRED');
    if (flow.stage === 'exception') fail('异常尚未处理，请等待经营者确认处理结果', 'EXCEPTION_OPEN');
    return flow;
  }
  function inspect(data, order, input) {
    allowed(data, order, input.driverId);
    if (!['arrived', 'departed'].includes(order.nodeReservation?.status) || order.deposit?.status !== 'paid' || order.reviewStatus !== 'confirmed') fail('请先由经营者完成到点登记与派车', 'HANDOFF_REQUIRED');
    const price = moneyValue(input.lockedPrice, '验宠确认总价');
    if (price < order.deposit.amount || price > 100000) fail('确认总价不能低于已付保证金，演示上限为 100000 元', 'INVALID_LOCKED_PRICE', 400);
    if (['identity', 'cage', 'handoff'].some((key) => input.checks?.[key] !== true)) fail('请逐项完成身份材料、笼具和现场交接核验', 'INSPECTION_INCOMPLETE', 400);
    const note = text(input.note, '验宠与费用说明');
    if (order.fulfillment?.inspection) {
      if (order.fulfillment.inspection.lockedPrice === price && order.fulfillment.inspection.note === note) return { order, idempotent: true, simulated: true };
      fail('本单已出具确认价，不可重复修改，请联系经营者处理', 'PRICE_ALREADY_LOCKED');
    }
    // Departed without inspection is allowed only for legacy demo handoffs; it still cannot start transport before payment.
    const amount = (Math.round(price * 100) - Math.round(order.deposit.amount * 100)) / 100;
    order.fulfillment = { stage: 'awaiting_payment', inspection: { lockedPrice: price, note, checks: { identity: true, cage: true, handoff: true }, driverId: input.driverId, operator: input.operator, inspectedAt: new Date().toISOString(), simulated: true }, invoice: { id: `BAL-${randomUUID()}`, total: price, deposit: order.deposit.amount, amount, status: 'unpaid', simulated: true }, events: [], exceptions: [] };
    order.priceStatus = 'driver_locked'; order.status = '待确认尾款';
    event(data, order, 'inspection', '司机已完成模拟验宠', { ...input, note });
    return { order, idempotent: false, simulated: true };
  }
  function payBalance(data, order, input) {
    if (!input.ownerAccount || (order.ownerAccount || order.userPhone) !== input.ownerAccount) fail('未找到当前用户的订单', 'ORDER_NOT_FOUND', 404);
    const flow = activeFlow(order), invoice = flow.invoice;
    const accepted = moneyValue(input.acceptedTotal, '确认总价');
    if (input.invoiceId !== invoice.id || accepted !== invoice.total) fail('费用信息不一致，请刷新后重新确认', 'BALANCE_PRICE_CHANGED');
    if (invoice.status === 'paid') return { order, idempotent: true, simulated: true };
    if (flow.stage !== 'awaiting_payment' || order.deposit?.status !== 'paid') fail('当前订单不可支付尾款', 'BALANCE_NOT_PAYABLE');
    Object.assign(invoice, { status: 'paid', paidAmount: invoice.amount, paidAt: new Date().toISOString(), paymentId: `PAY-${invoice.id}`, method: '模拟支付' });
    flow.stage = 'ready'; order.status = order.nodeReservation?.status === 'departed' ? '待司机出发' : '待离点交接'; order.priceStatus = 'paid';
    event(data, order, 'balance_paid', invoice.amount === 0 ? '用户已确认费用，无需补款' : '用户已模拟支付尾款', { operator: input.operator });
    return { order, idempotent: false, simulated: true };
  }
  function depart(data, order, input) {
    const route = allowed(data, order, input.driverId), flow = activeFlow(order);
    if (flow.departedAt) return { order, idempotent: true, simulated: true };
    if (flow.stage !== 'ready' || flow.invoice.status !== 'paid' || order.nodeReservation?.status !== 'departed') fail('用户确认费用并完成模拟尾款后才能出发', 'BALANCE_UNPAID');
    flow.stage = 'in_transit'; flow.currentCity = order.fromCity; flow.departedAt = order.nodeReservation.checkedOutAt;
    order.status = '运输中'; route.status = '运输中';
    event(data, order, 'depart', '司机模拟出发', { operator: input.operator, city: order.fromCity, occurredAt: flow.departedAt });
    return { order, idempotent: false, simulated: true };
  }
  function checkpoint(data, order, input) {
    const route = allowed(data, order, input.driverId), flow = activeFlow(order);
    if (!['in_transit', 'arrived'].includes(flow.stage)) fail('请先完成出发，已签收订单不能追加运输节点', 'NOT_IN_TRANSIT');
    const city = text(input.city, '本次到达城市', 20), next = route.cities.indexOf(city), current = route.cities.indexOf(flow.currentCity), end = route.cities.indexOf(order.toCity);
    if (next < 0 || next <= route.cities.indexOf(order.fromCity) || next < current || next > end) fail('节点必须位于本单顺向运输区段，不可回退或越过目的地', 'INVALID_CHECKPOINT');
    if (next === current) return { order, idempotent: true, simulated: true };
    const note = text(input.note, '节点记录说明');
    const planned = Date.parse(route.departureAt) + (Date.parse(route.arrivalAt) - Date.parse(route.departureAt)) * next / (route.cities.length - 1);
    flow.currentCity = city; flow.lastCheckpointAt = new Date(Math.max(planned, Date.parse(flow.departedAt), Date.parse(flow.lastCheckpointAt || flow.departedAt))).toISOString();
    flow.stage = city === order.toCity ? 'arrived' : 'in_transit'; order.status = city === order.toCity ? '待签收' : '运输中';
    event(data, order, 'checkpoint', city === order.toCity ? '已模拟到达目的城市' : '已更新模拟运输节点', { ...input, note, city, occurredAt: flow.lastCheckpointAt });
    return { order, idempotent: false, simulated: true };
  }
  function reportException(data, order, input) {
    allowed(data, order, input.driverId); const flow = order.fulfillment;
    const requestId = text(input.clientRequestId, '本次提交标识', 80), note = text(input.note, '异常情况');
    const previous = flow?.exceptions?.find((item) => item.clientRequestId === requestId);
    if (previous) {
      if (previous.note === note) return { order, idempotent: true, simulated: true };
      fail('本次提交标识已用于其他异常内容', 'IDEMPOTENCY_CONFLICT');
    }
    if (!flow || flow.stage === 'delivered') fail('请先完成验宠；已签收任务不能再次报异常', 'EXCEPTION_NOT_ALLOWED');
    if (flow.stage === 'exception') {
      fail('已有待处理异常，请等待经营者处理', 'EXCEPTION_OPEN');
    }
    flow.exception = { id: `EX-${order.id}-${flow.events.length + 1}`, clientRequestId: requestId, note, previousStage: flow.stage, previousStatus: order.status, status: 'open', reportedAt: new Date().toISOString(), simulated: true };
    flow.exceptions ||= []; flow.exceptions.push(flow.exception);
    flow.stage = 'exception'; order.status = '履约异常';
    event(data, order, 'exception', '司机上报履约异常', { ...input, note });
    return { order, simulated: true };
  }
  function resolveException(data, order, input) {
    const flow = order.fulfillment, issue = flow?.exception;
    if (!issue || issue.id !== input.exceptionId) fail('异常记录已变化，请刷新后处理', 'EXCEPTION_CHANGED');
    const note = text(input.note, '处理结果与继续履约说明');
    if (issue.status === 'resolved') {
      if (issue.resolution === note) return { order, idempotent: true, simulated: true };
      fail('该异常已处理，请刷新查看', 'EXCEPTION_RESOLVED');
    }
    issue.status = 'resolved'; issue.resolution = note; issue.resolvedAt = new Date().toISOString(); issue.resolvedBy = input.operator;
    const archived = flow.exceptions?.find((item) => item.id === issue.id); if (archived) Object.assign(archived, issue);
    flow.stage = issue.previousStage; order.status = issue.previousStatus;
    event(data, order, 'exception_resolved', '经营者已处理异常，恢复原流程', { ...input, note });
    return { order, simulated: true };
  }
  function receive(data, order, input) {
    const route = allowed(data, order, input.driverId), flow = activeFlow(order);
    const receiverName = text(input.receiverName, '实际签收人姓名', 40);
    if (input.receiverVerified !== true || input.petAccepted !== true) fail('请确认签收人身份及宠物交接情况', 'RECEIPT_INCOMPLETE', 400);
    if (flow.stage === 'delivered') {
      if (flow.receipt.receiverName === receiverName) return { order, idempotent: true, simulated: true };
      fail('签收已记录，不可重复修改', 'RECEIPT_ALREADY_RECORDED');
    }
    if (flow.stage !== 'arrived' || flow.currentCity !== order.toCity || flow.invoice.status !== 'paid') fail('须到达目的城市、付清模拟费用且无待处理异常，才能签收', 'RECEIPT_NOT_ALLOWED');
    flow.receipt = { receiverName, receiverVerified: true, petAccepted: true, signedAt: flow.lastCheckpointAt, recordedAt: new Date().toISOString(), operator: input.operator, simulated: true };
    flow.stage = 'delivered'; order.status = '已签收';
    event(data, order, 'receipt', '已完成模拟签收', { ...input, note: `签收人：${receiverName}`, city: order.toCity, occurredAt: flow.receipt.signedAt });
    if (route.orderIds.length && route.orderIds.every((id) => data.orders.find((o) => o.id === id)?.fulfillment?.stage === 'delivered')) { route.status = '已完成'; route.completedAt = new Date().toISOString(); log(data, 'ROUTE_COMPLETED', input.operator, { routeId: route.id }); }
    return { order, simulated: true };
  }
  return { allowed, inspect, payBalance, depart, checkpoint, reportException, resolveException, receive };
};

} };
  const cache = new Map();
  function requireModule(name) {
    if (name === 'node:crypto') return browserCrypto;
    if (!Object.hasOwn(modules, name)) throw new Error('Unsupported demo module');
    if (!cache.has(name)) {
      const module = { exports: {} }; cache.set(name, module);
      modules[name](module, module.exports, requireModule);
    }
    return cache.get(name).exports;
  }
  function readDemoData() {
    const value = local.getItem(dataKey);
    if (!value) throw new Error('演示数据尚未准备好，请重置本端演示。');
    return JSON.parse(value);
  }
  function writeDemoData(data) {
    try { local.setItem(dataKey, JSON.stringify(data)); }
    catch { throw new Error('浏览器无法保存演示数据，请允许网站存储，或清理本网站的演示数据后重试。'); }
  }
  const store = requireModule('./store');
  function seedDemo(store) {
  const data = store.demoData();
  data.orders = []; data.routes = []; data.auditLogs = []; data.availability = [];
  data.demo = { enabled: true, label: '纯静态预置场景 · 无真实订单', resetAt: new Date().toISOString() };
  // Deliberately ample virtual capacity lets reviewers try several scenarios.
  data.cityNodes.find((node) => node.id === 'NODE-GZ-TH').capacity = 12;
  store.write(data);
  const hydrated = store.read();
  hydrated.availability.forEach((slot) => { slot.capacity = 20; slot.occupied = 0; });
  store.write(hydrated);
  const slot = store.listAvailability({ city: '广州' })[0];
  const addDays = (date, count) => new Date(Date.parse(date + 'T00:00:00Z') + count * 86400000).toISOString().slice(0, 10);
  const ops = { operator: 'ops001' };
  function make(name, stage = 'paid', owner = '13800138000') {
    const order = store.createOrder({
      requestId: 'static-seed-' + name,
      pet: { name: name.split(' · ')[0], type: '猫', breed: '中华田园猫', weight: 5 }, fromCity: '广州', toCity: '郑州',
      pickup: { slotId: slot.id }, materials: { petPhoto: '虚拟宠物近照.jpg', vaccineCertificate: '虚拟免疫证明.jpg' },
      healthDeclaration: ['noDisease', 'notPregnant', 'safeHandling'],
      contactName: '虚拟寄件人', contactPhone: owner, pickupAddress: '广州市虚拟演示路1号',
      recipientName: '虚拟收件人', recipientPhone: '13800138009', recipientAddress: '郑州市虚拟演示路2号',
      careNote: '仅用于界面评审，没有真实宠物、支付、材料或运输。'
    }, owner);
    if (stage === 'unpaid') return order;
    store.payDeposit(order.id);
    if (stage === 'paid') return store.getOrder(order.id);
    if (stage === 'info') {
      store.reviewOrder(order.id, { ...ops, action: 'request_info', note: '演示补件：请补充一张清晰的站立全身照。' });
      return store.getOrder(order.id);
    }
    store.reviewOrder(order.id, { ...ops, action: 'approve', nodeId: 'NODE-GZ-TH', proposedPrice: order.quote.basePrice, note: '虚拟材料已核对，请确认运输方案。' });
    if (stage === 'approved') return store.getOrder(order.id);
    store.confirmOrder(order.id, { acceptedPrice: order.quote.basePrice });
    if (stage === 'confirmed') return store.getOrder(order.id);
    store.nodeCheckIn(order.id, ops);
    return store.getOrder(order.id);
  }
  make('奶糖 · 待付保证金', 'unpaid');
  make('豆包 · 待审核');
  make('可乐 · 待补材料', 'info');
  make('布丁 · 待确认方案', 'approved');
  make('麻薯 · 待编线', 'confirmed');
  const scenarios = [
    ['花卷 · 待验宠', 'inspection'], ['糯米 · 待付尾款', 'balance'], ['年糕 · 待出发', 'ready'],
    ['团子 · 运输中', 'transit'], ['橘子 · 待签收', 'arrived'], ['丸子 · 异常待处理', 'exception'], ['幸运 · 已签收', 'delivered']
  ].map(([name, stage]) => ({ order: make(name, 'arrived'), stage }));
  const route = store.createRoute({ ...ops, name: '猫狗专车 · 虚拟演示线', cities: ['广州', '武汉', '郑州'],
    departureAt: `${slot.date}T17:00:00+08:00`, arrivalAt: `${addDays(slot.date, 1)}T18:00:00+08:00`, capacity: 8, minOrders: 1 }).route;
  scenarios.forEach(({ order }) => store.addOrderToRoute(route.id, order.id, ops));
  store.assignRoute(route.id, { ...ops, driverId: 'DRV-001', vehicleId: 'VEH-001' });
  store.dispatchRoute(route.id, ops);
  const actor = { driverId: 'DRV-001', operator: 'driver001' };
  for (const { order, stage } of scenarios) {
    if (stage === 'inspection') continue;
    const inspected = store.fulfillmentAction('inspect', order.id, { ...actor, checks: { identity: true, cage: true, handoff: true }, lockedPrice: order.quote.basePrice, note: '虚拟验宠已完成，费用与确认方案一致。' }).order;
    if (stage === 'balance') continue;
    store.fulfillmentAction('payBalance', order.id, { ownerAccount: '13800138000', operator: '13800138000', invoiceId: inspected.fulfillment.invoice.id, acceptedTotal: inspected.fulfillment.invoice.total });
    store.nodeCheckOut(order.id, ops);
    if (stage === 'ready') continue;
    store.fulfillmentAction('depart', order.id, actor);
    store.fulfillmentAction('checkpoint', order.id, { ...actor, city: stage === 'transit' ? '武汉' : '郑州', note: '预置虚拟节点，已模拟检查毛孩子状态。' });
    if (stage === 'exception') store.fulfillmentAction('reportException', order.id, { ...actor, clientRequestId: 'static-seed-exception', note: '虚拟签收人暂时未到场，请总部确认交接安排。' });
    if (stage === 'delivered') store.fulfillmentAction('receive', order.id, { ...actor, receiverName: '虚拟收件人', receiverVerified: true, petAccepted: true });
  }
  make('小满 · 第二用户样例', 'unpaid', '13800138001');
  const partner = { account: 'partner001', role: 'partner', nodeId: 'NODE-GZ-TH' };
  const operator = { account: 'ops001', role: 'ops' };
  const approved = store.submitCapacityRequest(partner, { requestId: 'static-approved-capacity', date: addDays(slot.date, 3), capacities: { AM: 12, PM: 14 }, note: '预置已通过场景：新增两处下午虚拟笼位。' }).request;
  store.reviewCapacityRequest(approved.id, operator, { action: 'approve', note: '虚拟配置核对完成，通过生效。' });
  const returned = store.submitCapacityRequest(partner, { requestId: 'static-returned-capacity', date: addDays(slot.date, 4), capacities: { AM: 14, PM: 14 }, note: '预置退回场景。' }).request;
  store.reviewCapacityRequest(returned.id, operator, { action: 'return', note: '请确认下午人员排班后重新申报。' });
  store.submitCapacityRequest(partner, { requestId: 'static-pending-capacity', date: addDays(slot.date, 2), capacities: { AM: 14, PM: 12 }, note: '预置待审核场景，可演示总部通过或退回。' });
  const complete = store.read();
  complete.demo.staticVersion = 2;
  complete.demo.seedDate = addDays(slot.date, -1);
  store.write(complete);
}

  let startupError = '';
  try {
    const saved = local.getItem(dataKey);
    if (!saved || JSON.parse(saved)?.demo?.staticVersion !== 2) seedDemo(store);
  } catch (error) { startupError = error.message; }

  function sessionRegistry() { return JSON.parse(local.getItem(sessionsKey) || '{}'); }
  function saveSessions(sessions) { local.setItem(sessionsKey, JSON.stringify(sessions)); }
  function result(body, status = 200) { return new Response(status === 204 ? null : JSON.stringify({ simulated: true, ...body }), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' } }); }
  function fail(message, status = 400, code = 'DEMO_ERROR') { throw new store.StoreError(message, status, code); }
  const wrapped = (order) => ({ order });
  const items = (values) => ({ items: values });

  async function dispatch(url, method, token, body) {
    const pathname = url.pathname, query = Object.fromEntries(url.searchParams);
    if (pathname === '/health') return result({ ok: true, mode: 'static-demo', offline: true });
    if (startupError) fail(startupError, 503, 'DEMO_STORAGE_UNAVAILABLE');
    const sessions = sessionRegistry();
    if (pathname === '/api/auth/login' && method === 'POST') {
      const account = String(body.account || '').trim(), configured = accounts[account];
      if (!configured || body.password !== configured.password) fail('演示账号或密码错误，请使用页面提供的测试账号。', 401, 'INVALID_CREDENTIALS');
      if (!allowed(configured.role)) fail(kind === 'client' ? '请使用客户端的用户演示账号。' : '请使用工作端的运营、司机或合作机构账号。', 403, 'WRONG_PORTAL');
      const { password, ...profile } = configured;
      const session = { account, ...profile, expiresAt: Date.now() + 8 * 3600000, simulated: true };
      for (const [key, value] of Object.entries(sessions)) if (value.expiresAt <= Date.now()) delete sessions[key];
      const freshToken = 'DEMO-' + randomHex(24); sessions[freshToken] = session; saveSessions(sessions);
      return result({ token: freshToken, ...session });
    }
    const session = sessions[token];
    if (!session || session.expiresAt <= Date.now() || !allowed(session.role)) fail('请先登录演示账号。', 401, 'UNAUTHORIZED');
    if (pathname === '/api/auth/me' && method === 'GET') return result(session);
    if (pathname === '/api/auth/logout' && method === 'POST') { delete sessions[token]; saveSessions(sessions); return result({ ok: true }); }
    if (pathname === '/api/demo/reset' && method === 'POST') {
      if (session.role !== 'ops') fail('仅运营演示账号可执行此操作。', 403, 'FORBIDDEN');
      seedDemo(store); return result({ ok: true, message: '已恢复本端预置演示数据。' });
    }
    const role = pathname.split('/')[2];
    if (role !== session.role) fail('当前演示账号不能操作此角色页面。', 403, 'FORBIDDEN');
    const actor = { ...body, operator: session.account };
    const route = `${method} ${pathname}`;
    const table = {
      'POST /api/user/quote': () => ({ quote: store.createQuote(body) }),
      'GET /api/user/availability': () => ({ items: store.listAvailability(query), ...store.availabilityMeta(query) }),
      'GET /api/user/orders': () => items(store.listUserOrders(session.account)),
      'POST /api/user/orders': () => wrapped(store.createOrder(body, session.account)),
      'GET /api/ops/dashboard': () => store.dashboard(),
      'GET /api/ops/orders': () => items(store.listOrders(query)),
      'GET /api/ops/city-nodes': () => items(store.listCityNodes()),
      'GET /api/ops/node-calendar': () => store.nodeCalendar(query),
      'GET /api/ops/transport-resources': () => store.listTransportResources(),
      'GET /api/ops/routes': () => items(store.listRoutes()),
      'POST /api/ops/routes': () => store.createRoute(actor),
      'GET /api/ops/capacity-requests': () => items(store.listCapacityRequests(null, query)),
      'GET /api/driver/orders': () => items(store.listDriverOrders(session.driverId)),
      'GET /api/partner/node': () => store.partnerNode(session, query),
      'GET /api/partner/capacity-requests': () => items(store.listCapacityRequests(session)),
      'POST /api/partner/capacity-requests': () => store.submitCapacityRequest(session, body)
    };
    if (Object.hasOwn(table, route)) return result(table[route](), method === 'POST' && pathname.endsWith('/orders') ? 201 : 200);
    const match = pathname.match(/^\/api\/(user|ops|driver)\/(orders|routes|city-nodes|capacity-requests)\/([^/]+)(?:\/(.*))?$/);
    if (!match) fail('此演示操作不存在。', 404, 'NOT_FOUND');
    const [, , resource, id, action = ''] = match;
    if (role === 'user' && resource === 'orders') {
      const own = store.getUserOrder(id, session.account);
      if (method === 'GET' && !action) return result(wrapped(own));
      if (method !== 'POST') fail('不支持此演示操作。', 405);
      const actions = {
        'deposit/pay': () => store.payDeposit(id),
        'balance/pay': () => store.fulfillmentAction('payBalance', id, { ...actor, ownerAccount: session.account }),
        supplement: () => wrapped(store.supplementOrder(id, body)), confirm: () => store.confirmOrder(id, body),
        cancel: () => store.cancelOrder(id, body), reschedule: () => store.rescheduleOrder(id, body)
      };
      if (Object.hasOwn(actions, action)) return result(actions[action]());
    }
    if (role === 'driver' && resource === 'orders') {
      const own = store.getDriverOrder(id, session.driverId);
      if (method === 'GET' && !action) return result(wrapped(own));
      const actions = { inspection: 'inspect', depart: 'depart', checkpoint: 'checkpoint', exception: 'reportException', receipt: 'receive' };
      if (method === 'POST' && Object.hasOwn(actions, action)) return result(store.fulfillmentAction(actions[action], id, { ...actor, driverId: session.driverId }));
    }
    if (role === 'ops') {
      if (resource === 'city-nodes' && method === 'PATCH' && !action) return result(store.updateCityNode(id, actor));
      if (resource === 'capacity-requests' && method === 'POST' && action === 'review') return result(store.reviewCapacityRequest(id, session, body));
      if (resource === 'orders') {
        if (method === 'PATCH' && action === 'review') return result(store.reviewOrder(id, actor));
        if (method === 'PATCH' && action === 'status') return result(store.updateOrderStatus(id, body.status));
        const actions = { refund: () => store.processRefund(id, actor), 'exception/resolve': () => store.fulfillmentAction('resolveException', id, actor), 'node-check-in': () => store.nodeCheckIn(id, actor), 'node-check-out': () => store.nodeCheckOut(id, actor) };
        if (method === 'POST' && Object.hasOwn(actions, action)) return result(actions[action]());
      }
      if (resource === 'routes') {
        if (method === 'GET' && !action) return result({ route: store.getRoute(id) });
        const actions = { orders: () => store.addOrderToRoute(id, body.orderId, actor), 'remove-order': () => store.removeOrderFromRoute(id, body.orderId, actor), assign: () => store.assignRoute(id, actor), dispatch: () => store.dispatchRoute(id, actor) };
        if (method === 'POST' && Object.hasOwn(actions, action)) return result(actions[action]());
      }
    }
    fail('此演示操作不存在。', 404, 'NOT_FOUND');
  }

  window.fetch = async (input, options = {}) => {
    const request = typeof Request !== 'undefined' && input instanceof Request ? input : null;
    const url = new URL(request ? request.url : String(input), window.location.href);
    if (!(url.pathname.startsWith('/api/') || url.pathname === '/health')) return nativeFetch(input, options);
    // Even a accidentally configured API origin cannot send demo form data out.
    if (options.signal?.aborted || request?.signal?.aborted) throw new DOMException('Aborted', 'AbortError');
    try {
      const method = String(options.method || request?.method || 'GET').toUpperCase();
      const headers = new Headers(options.headers || request?.headers || {});
      const text = options.body === undefined ? (request && !['GET', 'HEAD'].includes(method) ? await request.text() : '') : options.body;
      const body = text ? JSON.parse(text) : {};
      if (!body || typeof body !== 'object' || Array.isArray(body)) fail('请输入有效的演示内容。');
      const token = (headers.get('Authorization') || '').replace(/^Bearer\s+/i, '');
      return await dispatch(url, method, token, body);
    } catch (error) { return result({ error: error.message || '演示操作失败', code: error.code || 'DEMO_ERROR' }, error.status || 400); }
  };

  function reset() {
    seedDemo(store); startupError = '';
  }
  window.PaichongStaticDemo = Object.freeze({ mode: 'static-demo', portal: kind, reset });
  function mountNotice() {
    const bar = document.createElement('div');
    bar.className = 'static-demo-notice';
    bar.setAttribute('role', 'note');
    bar.innerHTML = '<span><b>离线演示</b> · 虚拟数据 · 不跨端同步</span><button type="button">重置本端</button>';
    try {
      const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Shanghai', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
      if (readDemoData().demo.seedDate < today) bar.querySelector('span').textContent = '离线演示 · 样例日期已变化，请重置更新';
    } catch { /* The API exposes the storage error with an actionable message. */ }
    const style = document.createElement('style');
    style.textContent = '.static-demo-notice{box-sizing:border-box;display:flex;align-items:center;justify-content:space-between;gap:6px;width:100%;max-width:430px;margin:0 auto;padding:9px 12px;background:#eaf5ef;color:#426c5c;font:11px/1.5 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}.static-demo-notice b{font-weight:650}.static-demo-notice button{flex-shrink:0;border:1px solid #c9dfd2;border-radius:8px;background:#fff;color:#426c5c;padding:7px;font:inherit;min-height:36px}.static-demo-notice button:focus-visible{outline:2px solid #ea8b44;outline-offset:2px}';
    document.head.append(style); document.body.prepend(bar);
    bar.querySelector('button').addEventListener('click', () => {
      if (!window.confirm('恢复本端的预置虚拟订单？只清除本端演示操作，不影响另一端、云端或其他网站。')) return;
      try { reset(); window.location.reload(); } catch (error) { window.alert(error.message); }
    });
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mountNotice, { once: true });
  else mountNotice();
})();
